extended spacings
bbc/simorgh pull request #10353
Opened 2022-10-12 15:37 UTC by archibalderson

Resolves #NUMBER

Resolves #NUMBER

Added quintuple and sextuple spacings

**Code changes:**
- Added quintuple and sextuple spacings

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

2022-10-12 15:39 UTC, rebeccamcginn requested changes
.

2022-10-12 15:42 UTC, rebeccamcginn approved these changes

2022-10-13 08:01 UTC, DarioR01 approved these changes

2022-10-13 11:16 UTC, amoore108 commented
Looks good, although this will need added in a few other places to make it available via the `Theme`:

`withThemeProvider`:
https://github.com/bbc/simorgh/blob/41295add78689c69a9528afeb042255c5b1977de/src/app/components/ThemeProvider/withThemeProvider.tsx#L241 

Theme types:
https://github.com/bbc/simorgh/blob/41295add78689c69a9528afeb042255c5b1977de/src/app/models/types/theming.ts#L76-L77 

ideally the README as well to keep it up to date:
https://github.com/bbc/simorgh/blob/eaffc1b6893a6559a5e75e4a166ac174cc9b9b5b/src/app/components/ThemeProvider/README.md#L210-L211

2022-10-13 14:14 UTC, andrewscfc approved these changes
Thanks Archie!

2022-10-13 14:21 UTC, merged