Convert Footer to SitewideLinks
bbc/simorgh pull request #1045
Opened 2018-12-04 14:25 UTC by dr3

Resolves #1034

Creates SitewideLinks component out of Footer

- [ ] Tests added for new features
- [x] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

TESTING NOTES

This splits up the footer component so that the brand and links sections are separate and no longer nested. This means the 'footer' component no longer exists inside storybook and instead a SitewideLinks component exists, which is just the links section with no 'footer' wrapper.

No other changes should be visible

2018-12-04 16:31 UTC, ChrisBAshton requested changes
This follows what we agreed https://github.com/BBC-News/simorgh/issues/1034#issue-386864715

BUT - is it too late to make a suggestion?

I don't see the value in a `SitewideLinks` component. We don't plan on reusing it in our own designs, and we wouldn't expect other teams to want to reuse it as a component. It's a collection of simple presentational components - I think it's best handled in the `FooterContainer`.

The less nesting, the better IMO. Thoughts?

2018-12-04 16:31 UTC, ChrisBAshton commented on src/app/components/SitewideLinks/README.md
> +
Blank?

2018-12-04 16:54 UTC, ChrisBAshton submitted a review, later dismissed
Had a IRL chat with Drew, and now approve the concept of a SitewideLinks component, on the basis that:

1. This is _not_ just a component that pulls in a generic paragraph and a list. It's _very specifically styled_ to the footer, so is only useful in the sum of its parts, not its parts.
2. It does have value as a component in its own right (rather than living in our FooterContainer) as it could be used across lots of pages (not just article pages). Footers are generally the same across a site...

So fair enough.

Also nitpicked on the spelling of `SitewideLinks` vs `SiteWideLinks`, but ["sitewide" can count as a word in the same way as "website"](https://en.wiktionary.org/wiki/sitewide) so I'm happy to keep this as-is.

Approved! 🎉

2018-12-04 17:00 UTC, ChrisBAshton submitted a review, later dismissed

2018-12-05 09:34 UTC, sareh commented
Looks great! @dr3 Could you please add testing instructions in the PR description?  Explaining what part of Storybook stories have changed and the part of the page that James should look at regression testing when looking at this PR?

2018-12-05 11:05 UTC, sareh submitted a review, later dismissed
👍 Looks great!

2018-12-05 11:05 UTC, sareh commented on src/app/components/SitewideLinks/README.md
> +### Landmark Roles
👍 I like your explanation of usage, including the landmark contentinfo.

2018-12-05 15:21 UTC, sareh approved these changes

2018-12-06 10:20 UTC, ChrisBAshton approved these changes

2018-12-06 16:51 UTC, jamesbrumpton commented
LGTM

2018-12-07 10:25 UTC, merged