Use psammead-paragraph
bbc/simorgh pull request #1051
Opened 2018-12-05 11:08 UTC by sareh

Resolves #997

This PR uses `@bbc/psammead-paragraph`

- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2018-12-05 11:16 UTC, sareh commented
Failures in the build are due to https://www.npmjs.com/package/@bbc/psammead-paragraph not yet being public.

2018-12-05 11:50 UTC, bcmn submitted a review, later dismissed

2018-12-05 11:51 UTC, dr3 submitted a review, later dismissed

2018-12-05 12:54 UTC, pjlee11 submitted a review, later dismissed

2018-12-05 12:54 UTC, bcmn submitted a review, later dismissed

2018-12-06 15:44 UTC, dr3 commented on src/app/components/Text/__snapshots__/index.test.jsx.snap
>  // Jest Snapshot v1, https://goo.gl/fbAQLP
Snapshot needs updating

2018-12-10 14:11 UTC, bcmn requested changes
Otherwise looks good! 👍

2018-12-10 14:11 UTC, bcmn commented on src/app/components/Text/__snapshots__/index.test.jsx.snap
> -  font-size: 0.9375em;
These shouldn't have been removed from the snapshot, following [psammead#164](https://github.com/BBC-News/psammead/pull/164). I think it's a case of the cached version of the Psammead package being used -- bumping the requested version in `package.json` immediately causes these snapshots to fail.

2018-12-10 14:11 UTC, bcmn commented on package.json
> +    "@bbc/psammead-paragraph": "^0.1.1",
```suggestion
    "@bbc/psammead-paragraph": "^0.1.2",
```

See below.

2018-12-10 14:35 UTC, bcmn submitted a review, later dismissed

2018-12-10 18:23 UTC, dr3 submitted a review, later dismissed
👍

2018-12-11 14:36 UTC, dr3 approved these changes

2018-12-11 14:52 UTC, ChrisBAshton approved these changes

2018-12-12 09:15 UTC, merged