fix font order
bbc/simorgh pull request #10697
Opened 2023-03-10 13:19 UTC by Louis-Matsika

Resolves JIRA 1679

Overall changes
======
Add "Times New Roman" before Arial as our first backup font for reith qalam. Our current back upfont is too different from the main font, leading to bad content layout shift scores.

Code changes
======

- add `"Times New Roman"` on line 29 in `fontFamilies.ts`

Testing
======
1. run `yarn test`

Helpful Links
======

[content layout shift](https://web.dev/cls/)

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

2023-03-10 13:58 UTC, eagerterrier requested changes
tests need updating - see here for details https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635 

(relevant snippet below...)

```Summary of all failing tests
[29869](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29870)
 FAIL  src/app/components/Text/index.test.tsx
[29870](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29871)
  ● Text › should render the correct typography for the arabic service
[29871](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29872)

[29872](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29873)
    expect(element).toHaveStyle()
[29873](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29874)

[29874](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29875)
    - Expected
[29875](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29876)

[29876](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29877)
      color: rgb(20, 20, 20);
[29877](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29878)
    - fontFamily: "BBC Reith Qalam",Arial,Verdana,Geneva,Helvetica,sans-serif;
[29878](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29879)
    - fontSize: 0.9375rem;
[29879](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29880)
    - fontStyle: normal;
[29880](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29881)
    - fontWeight: 400;
[29881](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29882)
    - lineHeight: 1.5rem;
[29882](https://github.com/bbc/simorgh/actions/runs/4384894422/jobs/7676916635#step:10:29883)```

2023-03-24 15:55 UTC, mfonofm reviewed
Do we also need to make changes to `reithQalamFallback` in `psammead-styles > src > font-families`?

2023-03-24 17:24 UTC, mfonofm commented on src/app/legacy/psammead/psammead-styles/src/font-families.js
> +const reithQalamFallback = '"Times New Roman", Arial, Verdana, Geneva, Helvetica, sans-serif;';
nice, you'll just need to update the snapshots and run the linter to format your changes

2023-03-24 21:20 UTC, eagerterrier requested changes
Linting and then we’re done

2023-04-19 09:12 UTC, shayneahchoon approved these changes

2023-04-21 11:31 UTC, eagerterrier approved these changes
phew!

2023-04-21 12:57 UTC, merged