Wsteama 844 removes amphtml from homepages
bbc/simorgh pull request #11151
Opened 2023-10-24 11:50 UTC by Nabeel1276

Resolves JIRA https://jira.dev.bbc.co.uk/browse/WSTEAMA-844

Overall changes
======
Removed amphtml from homepages

Code changes
======

- In the "HomePage" file, the "hasAmpPage" Prop is set to "true" by default. Changing "hasAmpPage" to "false" results in the removal of amphtml from homepages.

Testing
======
First result for searching a service is the canonical page, rather than the amp page.

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

2023-10-24 13:27 UTC, karinathomasbbc commented on src/app/pages/HomePage/HomePage.tsx
> -      <Ad slotType="leaderboard" />
Oh dear, this seems to have been removed by accident (which is causing some of the tests to fail). Can we put this back 🙏 ?

2023-10-24 13:29 UTC, karinathomasbbc commented on .yarn/cache/@next-swc-darwin-arm64-npm-13.5.5-6a6410e73d-8.zip
**Note to reviewers:** We have included this library because some of us (with the new chips?) require it. We thought it was safe enough to add to this PR, as it really only affects local development.

2023-10-24 13:29 UTC, karinathomasbbc commented on src/app/pages/HomePage/HomePage.tsx
> -import MPU from '../../components/Ad/MPU';
This needs to be put back in.

2023-10-24 15:15 UTC, karinathomasbbc commented on src/app/pages/HomePage/HomePage.tsx
> +        hasAmpPage={false}
I am surprised that no unit / integration tests have failed as a result of this change, and I think we should perhaps add a unit test, to capture the new behaviour, just to be on the safe side

2023-10-24 15:15 UTC, karinathomasbbc requested changes, later dismissed
Let's add a unit test for the new behaviour

2023-10-24 15:55 UTC, amoore108 approved these changes

2023-10-26 10:29 UTC, pvaliani approved these changes

2023-10-26 11:32 UTC, merged