WSTEAMA 886 Launch Simorgh route persian/afghanistan service to homepage on live environment
bbc/simorgh pull request #11211
Opened 2023-12-04 11:35 UTC by holchris

Resolves JIRA [number]

Overall changes
======
_A very high-level summary of easily-reproducible changes that can be understood by non-devs, and why these changes where made._

Code changes
======

- _A bullet point list of key code changes that have been made._

Testing
======
1. _List the steps used to test this PR._

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

2023-12-04 16:09 UTC, karinathomasbbc commented on src/app/routes/utils/regex/utils/index.js
>    return `/:idx(${idxPageRegex}):amp(${ampRegex})?`;
We can just use the `idxRegex` value as declared above - no need to use a separate variable

```suggestion

  return `/:idx(${idxRegex}):amp(${ampRegex})?`;
```

2023-12-04 16:11 UTC, karinathomasbbc commented on src/app/routes/topic/index.js
> +  path: [topicPath && '/persian/afghanistan'],
Ah... this won't work 😿 

The path needs to be an array of values, containing the regex for all topics (`topicPath`) as well as the "regex" (but really it's just hardcoded) for the /persian/afghanistan page)
 
```suggestion
  path: [topicPath, '/persian/afghanistan'],
```

2023-12-04 16:12 UTC, karinathomasbbc requested changes
See comments ☝️

2023-12-06 10:12 UTC, shayneahchoon approved these changes

2023-12-06 11:36 UTC, karinathomasbbc requested changes

2023-12-06 11:36 UTC, karinathomasbbc commented on src/app/routes/utils/regex/utils/index.js
> +  'persian/afghanistan',
This is not required here - /persian/afghanistan is not a homepage, but a topic page. The changes to src/app/routes/topic/index.js and to `getIdxPageRegex` below are the code to launch /persian/afghanistan to live. We only need to include korean and pashto in the list of homepage services to migrate here.

2023-12-06 12:40 UTC, karinathomasbbc approved these changes
Nice!

2023-12-11 13:01 UTC, alex-magana approved these changes
LGTM.

2023-12-12 10:30 UTC, merged