WSTEAMA-972 Message banner update for app release
bbc/simorgh pull request #11323
Opened 2024-02-15 09:59 UTC by Nabeel1276

https://jira.dev.bbc.co.uk/browse/WSTEAMA-972
Overall changes
======
_A very high-level summary of easily-reproducible changes that can be understood by non-devs, and why these changes where made._

Code changes
======

Added visual prominence and visual style support for billboard.
Testing
======
added unit tests

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

2024-02-15 12:29 UTC, pvaliani approved these changes
Nice, good job

2024-02-15 12:32 UTC, LilyL0u approved these changes

2024-02-15 13:30 UTC, louisearchibald approved these changes
Nice 😃

2024-02-16 09:08 UTC, karinathomasbbc requested changes
Can we update the fixture data for the Afrique homepage, so that we can see these changes in Storybook?

2024-02-19 09:50 UTC, karinathomasbbc approved these changes

2024-02-19 12:44 UTC, merged