npm audit in CI
bbc/simorgh pull request #1145
Opened 2019-01-09 17:34 UTC by sareh

Resolves #NUMBER

- Add audit-ci to run in script `audit:ci`
- Use `npm run audit:ci` in Travis & Jenkins

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-01-09 17:45 UTC, sareh commented
This build on Travis passed here: https://travis-ci.org/bbc/simorgh/jobs/477454850#L508-L529
and on Jenkins: https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh/detail/npm-audit-ci/1/pipeline/

Now I will purposefully add a dependency that has a vulnerability, to demonstrate that both Travis & Jenkins will exit with a non-zero exit code and cause the build to fail.

2019-01-09 17:57 UTC, sareh commented
I found this advisory stating that `merge@1.2.0` has vulnerabilities of low severity. https://www.npmjs.com/advisories/722  I will add this as a dependency and expect the Travis & Jenkins pipelines to fail.

2019-01-10 10:26 UTC, sareh commented
Jenkins job exited and failed correctly. Also correctly reported 9 low-severity vulnerabilities.

<img width="1093" alt="screen shot Jenkins CI job" src="https://user-images.githubusercontent.com/3028997/50962283-cea9f800-14c1-11e9-8683-d12b60187526.png">
https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/simorgh/detail/npm-audit-ci/2/pipeline

Travis CI job also exited and failed correctly, reporting the 9 low-severity vulnerabilities:
https://travis-ci.org/bbc/simorgh/jobs/477464165
<img width="874" alt="screen shot travis CI job" src="https://user-images.githubusercontent.com/3028997/50962425-20528280-14c2-11e9-8994-13dc1847280d.png">

2019-01-10 12:05 UTC, ChrisBAshton commented on package.json
> +    "audit-ci": "^1.2.1",
What was the reason for adding a dependency when we can run `npm audit` directly?

2019-01-10 12:06 UTC, dr3 requested changes

2019-01-10 12:06 UTC, dr3 commented on Makefile
> +	cd ${APP_DIRECTORY}; npm run audit:ci;
This doesn't feel like an install step, but more of a tests step

2019-01-10 12:26 UTC, sareh commented on package.json
> +    "audit-ci": "^1.2.1",
I looked at `npm audit` directly initially.  It just reports and does not ever give a non-zero response code.

It is possible to use `npm audit --parseable` to give an output, however it doesn't show you the number of vulnerabilities you get - there should be 9 low-severity vulnerabilities here: 
`npm audit --parseable` output:
```
install	merge	low	npm install merge@1.2.1	Prototype pollution	https://nodesecurity.io/advisories/722	merge	N
update	merge	low	npm update merge --depth 9	Prototype pollution	https://nodesecurity.io/advisories/722	jest>jest-cli>jest-haste-map>sane>exec-sh>merge	N
```
An alternative `npm audit --json` gives more verbose output, including the number and severity of vulnerabilities. 
To use this, I'd need to parse the JSON output. It appears that `audit-ci` already handles this and has test coverage too: https://github.com/IBM/audit-ci/blob/master/lib/npm-auditer.js 

So I decided to use this here.

2019-01-10 12:40 UTC, dr3 submitted a review, later dismissed

2019-01-10 12:48 UTC, bcmn submitted a review, later dismissed
Looks really good! Thanks :)

2019-01-10 13:13 UTC, dr3 approved these changes
![](https://media.giphy.com/media/3oz8xRF0v9WMAUVLNK/giphy.gif)

2019-01-10 13:35 UTC, bcmn approved these changes

2019-01-11 10:34 UTC, merged