WSTEAMA-1458 - Setup static assets for 2nd preview environment
bbc/simorgh pull request #12215
Opened 2024-11-28 14:33 UTC by louisearchibald

Resolves JIRA [[1458](https://jira.dev.bbc.co.uk/browse/WSTEAMA-1458)]

Overall changes
======
Sets up static assets in Simorgh for a secondary preview environment

Code changes
======

- _A bullet point list of key code changes that have been made._

Testing
======
1. _List the steps used to test this PR._

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

2024-11-28 15:28 UTC, karinathomasbbc commented on envConfig/preview1.env
> +SIMORGH_PUBLIC_STATIC_ASSETS_PATH=/ws/simorgh-preview1-assets/public/
Would it be better to keep the name in line with the new simorgh preview name?
```suggestion
SIMORGH_PUBLIC_STATIC_ASSETS_PATH=/ws/simorgh1-preview-assets/public/
```

2024-11-28 15:28 UTC, karinathomasbbc commented on envConfig/preview2.env
> +SIMORGH_PUBLIC_STATIC_ASSETS_PATH=/ws/simorgh-preview2-assets/public/
```suggestion
SIMORGH_PUBLIC_STATIC_ASSETS_PATH=/ws/simorgh2-preview-assets/public/
```

2024-11-28 15:31 UTC, louisearchibald commented on envConfig/preview1.env
> +SIMORGH_PUBLIC_STATIC_ASSETS_PATH=/ws/simorgh-preview1-assets/public/
Thanks, changed now for both

2024-11-29 11:38 UTC, pvaliani approved these changes
LGTM

2024-11-29 12:29 UTC, karinathomasbbc approved these changes
Thanks for making the changes!

2024-12-05 15:10 UTC, andrewscfc requested changes

2024-12-05 15:10 UTC, andrewscfc commented on package.json
> +    "build:preview1": "cp envConfig/preview1.env .env && NODE_ENV=production webpack",
```suggestion
    "build:preview": "cp envConfig/preview1.env .env && NODE_ENV=production webpack",
    "build:preview1": "cp envConfig/preview1.env .env && NODE_ENV=production webpack",
```
As in https://github.com/bbc/simorgh-infrastructure/pull/1863#discussion_r1871493111 we need to maintain backward compatibility as `TARGET_ENV` is [not configurable](https://github.com/bbc/simorgh-infrastructure/blob/651675c84c9e17a8d78793a16b4a7b0f45dd0846/packages/preview-deploy/lib/preview-deploy-stack.js#L84) yet. 

I appreciate this wasn't in the ticket, this detail was missed sorry

2024-12-05 15:33 UTC, andrewscfc approved these changes

2024-12-10 12:36 UTC, merged