Make Cypress Tests Environment Agnostic
bbc/simorgh pull request #1292
Opened 2019-02-14 12:00 UTC by jamesbrumpton

This makes the Cypress tests environment agnostic so that we can run them against all environments.

Resolves #1263 

**Overall change:** We've made the Cypress tests environment agnostic but also pointed the `LIVE` `BASE_URL` to `Mozart_api`.

**Code changes:**

- _Make Cypress tests agnostic._
- _Point `LIVE BASE_URL` to `Mozart_api`._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-02-14 12:13 UTC, dr3 requested changes

2019-02-14 12:13 UTC, dr3 commented on cypress.json
> +}
```suggestion
}

```
Just needs an EOF blank line

2019-02-14 12:13 UTC, dr3 commented on .env
> +SIMORGH_BASE_URL=http://localhost:7080
This file shouldn't have been changed, not sure @pjlee11's trick worked. Can be reset with `git checkout latest .env`

2019-02-14 13:47 UTC, dr3 commented on .env
> +SIMORGH_BASE_URL=http://localhost:7080
```suggestion
```

2019-02-14 13:55 UTC, dr3 reviewed
👍 LGTM, wont officially approve though as I paired :)

This will fail on Live however as Live Asset `c9rpqy7pmypo` doesn't have an inline link. Jim is looking at fixing that

2019-02-14 14:03 UTC, pjlee11 reviewed
Looks sensible to me. Is `https://www.mozart-routing.api.bbci.co.uk` publicly available? I'm trying to think if there are any cases where `SIMORGH_BASE_URL` might fail if there is a cert/exception to be confirmed at mozart routing

2019-02-14 14:34 UTC, dr3 commented
@pjlee11 It is public, this is needed purely untill the STM change

2019-02-14 15:57 UTC, pjlee11 commented
I think with the fact we have to confirm the HTTPS exception (see screenshot) the Cypress tests may fail to get data when using that `SIMORGH_BASE_URL`. 

TL;DR - I'm 90% sure this will fail the LIVE E2Es in our deployment

![image](https://user-images.githubusercontent.com/7791726/52799104-20b9dc80-3071-11e9-8fb3-d5a914a4e5c7.png)

2019-02-14 17:51 UTC, dr3 commented
This is now blocked on https://github.com/bbc/simorgh/pull/1294

2019-02-15 09:51 UTC, sareh requested changes
Looks great so far. There are some comments to tidy the tests up.

2019-02-15 09:51 UTC, sareh commented on cypress/integration/footerSpec.js
>      // Only 'c9rpqy7pmypo' & 'c85pqyj5m2ko' are available within the PROD enviroment
You can remove this comment from here. 
```suggestion
```

2019-02-15 09:51 UTC, sareh commented on cypress/integration/headerSpec.js
>      // Only 'c9rpqy7pmypo' & 'c85pqyj5m2ko' are available within the PROD enviroment
You can remove this
```suggestion
```

2019-02-15 09:51 UTC, sareh commented on cypress/integration/metaNewsSpec.js
>      // Only 'c9rpqy7pmypo' & 'c85pqyj5m2ko' are available within the PROD enviroment
```suggestion
```

2019-02-15 09:51 UTC, sareh commented on cypress/integration/metaPersianSpec.js
>      // Only 'c9rpqy7pmypo' & 'c85pqyj5m2ko' are available within the PROD enviroment
```suggestion
```

2019-02-15 09:51 UTC, sareh commented on cypress/integration/newsBodySpec.js
>      // Only 'c9rpqy7pmypo' & 'c85pqyj5m2ko' are available within the PROD enviroment
```suggestion
```

2019-02-15 09:51 UTC, sareh commented on cypress/integration/persianBodySpec.js
>      // Only 'cwv2xv848j5o' is available within the PROD enviroment
```suggestion
```

2019-02-15 09:51 UTC, sareh commented on cypress/integration/newsBodySpec.js
> +  // it('should have a working first inline link', () => {
Instead of commenting out this test, I'd suggest changing the assertion, so we continue to test the first inline link of a page.

2019-02-19 15:58 UTC, bcmn commented
Currently the metadata Cypress tests have hard-coded values for the OpenGraph url tag.

[In `metaNewsSpec`](https://github.com/BBC-News/simorgh/blob/6dd1bf4ffb4b627664da9537abac644c07090032/cypress/integration/metaNewsSpec.js#L83).

[In `metaPersianSpec`](https://github.com/BBC-News/simorgh/blob/6dd1bf4ffb4b627664da9537abac644c07090032/cypress/integration/metaPersianSpec.js#L39).

This means the Cypress tests fail when you run `npm run test:e2e:live_env`. I think we'd want to replace it with something like:

```
openGraphMeta(
    'شاید خیلی طول نکشد که زمانی برسد که وقتی خسته هستید و مثلا هوس فنجان قهوه‌ای را کردید، پهپادی را ببینید که با قهوه سراغتان می‌آید.',
    'https://news.files.bbci.co.uk/ws/img/logos/og/persian.png',
    'BBC News فارسی',
    'fa',
    'BBC News فارسی',
    'پهپادی که برایتان قهوه می‌آورد',
    'article',
    `https://www.bbc.com/persian/articles/${config.assets.persian}`,
  );
```

2019-02-19 17:54 UTC, sareh approved these changes

2019-02-20 09:43 UTC, bcmn approved these changes

2019-02-20 10:02 UTC, bcmn commented
Merging as tested by Sareh, James & I.

2019-02-20 12:28 UTC, dr3 approved these changes

2019-02-20 13:45 UTC, merged

2019-02-20 13:45 UTC, ChrisBAshton commented
Merged despite Jenkins fail, because Jenkins was consistently passing tests etc, this looks like an internal workspace-clearing issue. Investigating separately.