Adding Cypress tests for AMP metadata
bbc/simorgh pull request #1377
Opened 2019-03-04 14:57 UTC by jamesbrumpton

Resolves #1375 

**Overall change:** _Adding Cypress tests for AMP metadata._

**Code changes:**

- _Adding Cypress tests, which check the metadata on AMP pages._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-03-05 10:00 UTC, dr3 requested changes

2019-03-05 10:00 UTC, dr3 commented on cypress/support/metaTestHelper.js
> +  // const { language } = data.metadata.passport;
???

2019-03-05 10:00 UTC, dr3 commented on cypress/support/metaTestHelper.js
> +export const retrieveAMPMetadata = data => {
Im not sure why metadataAssertion and retrieveAMPMetadata are seperate, they seem to do almost exactly the same things? Maybe they can be consolidated?

2019-03-05 14:45 UTC, ChrisBAshton submitted a review, later dismissed
I'd rename the function so it's clear what we're actually doing. But otherwise great! 👍

2019-03-05 14:45 UTC, ChrisBAshton commented on cypress/support/metaTestHelper.js
> +    retrieveData(windowData);
```suggestion
    checkDataMatchesMetadata(windowData);
```

2019-03-05 14:46 UTC, sareh requested changes
Looks great so far. Just one comment added.

2019-03-05 14:46 UTC, sareh commented on cypress/support/metaTestHelper.js
> +export const metadataAssertionAMP = service => {
We'll want to check the `lang` attribute exists on AMP pages as well as canonical pages, so I believe you can use just `metadataAssertion` and not need `metadataAssertionAMP`.

2019-03-06 15:01 UTC, dr3 approved these changes

2019-03-06 15:46 UTC, sareh approved these changes
👍 Looks great! Great work on investigating the differences in AMP and Canonical pages and then updating the Cypress tests to reflect that.

2019-03-06 15:51 UTC, merged