Bump Psammead components and use new fontface
bbc/simorgh pull request #1394
Opened 2019-03-08 13:34 UTC by dr3

Resolves #1276

**Overall change:** Bump Psammead components and use new fontface

**Code changes:**

- Pulls in all new changes from psammead
- Uses all 6 font faces and new font family

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-03-08 17:00 UTC, sareh requested changes
Looks great. Just a note about the fonts being pulled in!

2019-03-08 17:00 UTC, sareh commented on src/app/lib/globalStyles.js
> +  ${F_REITH_SANS_BOLD_ITALIC}
```suggestion
```
We should only have these fonts on our News pages:
```
Serif Medium
Serif Medium Italic
Sans Regular
Sans Regular Italic
Sans Bold
Serif Light (only required for the Most read component, which we currently do not have)
```
Source: https://github.com/bbc/simorgh/issues/1311

2019-03-08 17:13 UTC, sareh commented on src/app/lib/globalStyles.js
> +  ${F_REITH_SANS_BOLD_ITALIC}
Having checked with Jim regarding this change in fonts, I've now updated issue #1311 & I'll remove this suggestion.

2019-03-11 13:14 UTC, sareh requested changes
Just a missing `font-family` value. Otherwise it looks great.

2019-03-11 13:14 UTC, sareh commented on src/app/components/Timestamp/index.jsx
> +  font-family: ${GEL_FF_REITH_SANS};
```suggestion
  font-family: ${GEL_FF_REITH_SANS};
  font-weight: 500;
```
I believe everywhere you've added a `font-family`, you should have the relevant `font-weight` value used as well.

2019-03-11 13:27 UTC, dr3 commented on src/app/components/Timestamp/index.jsx
> +  font-family: ${GEL_FF_REITH_SANS};
Really? even when its not bold?

2019-03-11 13:57 UTC, dr3 commented on src/app/components/Timestamp/index.jsx
> +  font-family: ${GEL_FF_REITH_SANS};
We currently dont define a value for regular https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js#L4-L9 so I think we should maintain not defining one here for now

2019-03-11 13:59 UTC, sareh commented on src/app/components/Timestamp/index.jsx
> +  font-family: ${GEL_FF_REITH_SANS};
Sounds good.  I was under the impression that Regular used the `font-weight` value equivalent of `normal` which is `500`. But that is apparently not the case.  We should separately discuss which font-weight Regular should use with UX.

2019-03-11 13:59 UTC, sareh submitted a review, later dismissed
👍 Looks great.

2019-03-11 16:30 UTC, twinlensreflex submitted a review, later dismissed
LGTM 👍

2019-03-12 10:07 UTC, twinlensreflex submitted a review, later dismissed

2019-03-12 10:08 UTC, sareh submitted a review, later dismissed
👍 Looks good! Thanks for adding all the changes in the PR description, for greater visibility. 💯

2019-03-12 16:15 UTC, pjlee11 approved these changes

2019-03-12 16:16 UTC, sareh approved these changes

2019-03-12 16:22 UTC, merged