Canonical consent banner tests
bbc/simorgh pull request #1421
Opened 2019-03-15 11:19 UTC by jamesbrumpton

Resolves #1413 

**Overall change:** _Adding Cypress tests for the Cookie Banner on canonical pages ._

**Code changes:**

- _Testing the banner appears._
- _Testing that the banner disappears once relevant buttons have been clicked._
- _Testing that the cookies are assigned the relevant values._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-03-15 14:55 UTC, dr3 commented on cypress.json
> +
Unneeded added line

2019-03-18 09:15 UTC, dr3 requested changes
Can you please look into cypress network request testing https://docs.cypress.io/guides/guides/network-requests.html#Testing-Strategies

Would be good to test the request to `https://cookie-oven.api.bbc.co.uk/ckns_policy/*`

2019-03-18 09:15 UTC, dr3 commented on cypress/integration/cookieBanner.js
> +    retrieveCookieValue('ckns_policy', '000');
We should call `expectCookieExpiryDateOneYear` on `ckns_privacy` and `ckns_policy` before banner interation

2019-03-18 10:57 UTC, dr3 requested changes
More info on the client side cookie oven request we should test for
```
Cypress on LIVE
Client side request is made to 'https://cookie-oven.api.bbc.com/ckns_policy/000'
Client side request is made to 'https://cookie-oven.api.bbc.com/ckns_policy/111'

Cypress on TEST
Client side request is made to 'https://cookie-oven.test.api.bbc.com/ckns_policy/000'
Client side request is made to 'https://cookie-oven.test.api.bbc.com/ckns_policy/111'

Cypress on LOCAL
Client side request is made to 'http://localhost:7080/ckns_policy/000'
Client side request is made to 'http://localhost:7080/ckns_policy/111'
```

2019-03-19 15:40 UTC, ChrisBAshton commented
Closed in favour of https://github.com/bbc/simorgh/pull/1439

2019-03-19 15:40 UTC, closed without merging