Update psammead dependencies
bbc/simorgh pull request #1460
Opened 2019-03-22 09:45 UTC by ChrisBAshton

Resolves #1172

**Overall change:** Pulls in latest Psammead dependencies. Needed for latest caption styling.

**Code changes:**

- Updated all latest psammead dependencies.
- Resolved `js-yaml` subdependencies to be a version that doesn't have a vulnerability
- Updates snapshots (Psammead components have updated to use `rem` over `em`)

Regression check needed.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-03-22 11:56 UTC, dr3 requested changes

2019-03-22 11:56 UTC, dr3 commented on package.json
> +    "@bbc/gel-foundations": "^0.3.0",
Last time I did this James wanted a list of all possible changes to these packages like https://github.com/bbc/simorgh/pull/1394. Its made by comparing the versions and manually copying the changes in their changelog

2019-03-22 13:33 UTC, dr3 submitted a review, later dismissed
![](https://media.giphy.com/media/l46CwVyMaDnl1pRhC/source.gif)

2019-03-22 16:05 UTC, dr3 submitted a review, later dismissed

2019-03-25 09:13 UTC, sareh submitted a review, later dismissed
👍 Looks good. I noted that now that we have removed the background colour of the caption, the padding (1rem, 16px) makes the text look indented. 

<img width="788" alt="Screen Shot of caption with 1rem padding" src="https://user-images.githubusercontent.com/3028997/54907707-13003e00-4ede-11e9-969a-15745de7aca0.png">

We'll likely want to check with UX whether this is desired.

2019-03-25 12:52 UTC, ChrisBAshton commented
Failed UX review, raised bug with gel-foundations: https://github.com/bbc/psammead/issues/388

2019-03-25 12:52 UTC, ChrisBAshton commented
> 👍 Looks good. I noted that now that we have removed the background colour of the caption, the padding (1rem, 16px) makes the text look indented.
> 
> <img alt="Screen Shot of caption with 1rem padding" width="788" src="https://user-images.githubusercontent.com/3028997/54907707-13003e00-4ede-11e9-969a-15745de7aca0.png">
> 
> We'll likely want to check with UX whether this is desired.

We've now raised https://github.com/bbc/psammead/issues/382 for this.

2019-03-25 12:54 UTC, ChrisBAshton commented
Given we've still work to do on figcaption, let's fix https://github.com/bbc/psammead/issues/382 before continuing with this PR.

2019-03-25 16:17 UTC, ChrisBAshton commented
Blocked on https://github.com/bbc/psammead/pull/393.

2019-03-27 10:35 UTC, ChrisBAshton commented
Now blocked on #398.

2019-03-28 14:45 UTC, ChrisBAshton commented
Now blocked on https://github.com/bbc/psammead/pull/381.

2019-03-29 12:07 UTC, ChrisBAshton commented
Now blocked on https://github.com/bbc/psammead/pull/406.

2019-03-29 14:15 UTC, pjlee11 submitted a review, later dismissed
LGTM 👍

2019-03-29 16:57 UTC, dr3 submitted a review, later dismissed

2019-03-29 17:08 UTC, ChrisBAshton commented
Blocked on https://github.com/bbc/psammead/pull/410 :(

2019-04-01 15:21 UTC, sareh commented on .env
> +SIMORGH_BASE_URL=http://localhost:7080
Can you please revert this file's changes?

2019-04-01 15:29 UTC, sareh approved these changes
👍 Looks great.

2019-04-01 15:29 UTC, pjlee11 approved these changes

2019-04-01 15:36 UTC, dr3 commented
Have popped this straight into ready for test, This can be UX reviewed in parallel. Any changes will likely be raised in new issues

2019-04-03 10:43 UTC, merged