Remove uglifyjs plugin
bbc/simorgh pull request #1480
Opened 2019-03-25 11:39 UTC by pjlee11

Resolves #1479

**Overall change:** _Remove the extraneous dependency `uglifyjs-webpack-plugin` _

**Code changes:**

- _Removes `uglifyjs-webpack-plugin` which was previously a required dependency of offline-plugin. Source: https://github.com/bbc/simorgh/pull/1117_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-03-25 12:09 UTC, dr3 requested changes

2019-03-25 12:09 UTC, dr3 commented on package.json
> +    "test:lighthouse": "lighthouse-ci http://localhost:7080/news/articles/cl55zn0w0l4o --performance=80 --pwa=62 --accessibility=100 --best-practices=93 --seo=70 && lighthouse-ci http://localhost:708
???

2019-03-25 12:36 UTC, pjlee11 commented on package.json
> +    "test:lighthouse": "lighthouse-ci http://localhost:7080/news/articles/cl55zn0w0l4o --performance=80 --pwa=62 --accessibility=100 --best-practices=93 --seo=70 && lighthouse-ci http://localhost:708
Weird .... I'll pull latest

2019-03-25 12:54 UTC, dr3 submitted a review, later dismissed

2019-03-25 16:08 UTC, sareh submitted a review, later dismissed

2019-03-26 17:49 UTC, dr3 approved these changes

2019-03-27 09:12 UTC, ChrisBAshton approved these changes
Whilst I agree we should remove unused dependencies, first I'd ask _why_ we're not using UglifyJS?

Just checked a production build and our main.js is un-uglified and weighs 69KB. Tweaked the Webpack config to explicitly use `uglifyjs` and the result was... no difference.

Turns out Webpack v4+ automatically minifies your code: https://webpack.js.org/guides/production/#minification

_Think_ it's using uglify under the hood. So yes, should be safe to remove 👍

2019-03-27 10:57 UTC, merged