Update "Using environment builds locally"
bbc/simorgh pull request #1488
Opened 2019-03-25 12:58 UTC by pjlee11

~Resolves #NUMBER~

**Overall change:** _Make the read me accurate_

**Code changes:**

~- _A bullet point list of key code changes that have been made._~
~- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._~

---

~- [ ] I have assigned myself to this PR and the corresponding issues~
~- [ ] Tests added for new features~
- [ ] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-03-25 16:43 UTC, ChrisBAshton requested changes

2019-03-25 16:43 UTC, ChrisBAshton commented on README.md
> +- In `envConfig/test.env` change the value of a to `LOG_DIR='/var/log/simorgh'`
"change the value of a to"

?

2019-03-25 16:49 UTC, pjlee11 commented on README.md
> +- In `envConfig/test.env` change the value of a to `LOG_DIR='/var/log/simorgh'`
😂  🤦‍♂️

2019-03-25 16:49 UTC, pjlee11 commented on README.md
> +- In `envConfig/test.env` change the value of a to `LOG_DIR='/var/log/simorgh'`
```suggestion
- In `envConfig/test.env` change the value of `LOG_DIR='/var/log/simorgh'` to `LOG_DIR='log'`
```

2019-03-25 16:49 UTC, pjlee11 commented on README.md
> +- In `envConfig/live.env` change the value of a to `LOG_DIR='/var/log/simorgh'`
```suggestion
- In `envConfig/live.env` change the value of `LOG_DIR='/var/log/simorgh'` to `LOG_DIR='log'`
```

2019-03-25 17:32 UTC, dr3 approved these changes

2019-03-26 06:54 UTC, ChrisBAshton approved these changes

2019-03-26 11:55 UTC, jamesbrumpton commented
👍

2019-03-26 14:46 UTC, merged