refactors timestamp api, resolves #1446
bbc/simorgh pull request #1519
Opened 2019-03-29 16:58 UTC by ChrisBAshton

Resolves #1446

**Overall change:** Refactors API - take children generically, removes `prefix`/`suffix` props. Also refactors the main Timestamp container to be more readable.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-04-01 09:58 UTC, twinlensreflex submitted a review, later dismissed
looks good to me 👍

2019-04-01 11:07 UTC, dr3 commented on src/app/containers/Timestamp/index.jsx
> +]; // eslint-disable-line
`// eslint-disable-line` is there to avoid it taking up 14 lines

2019-04-01 11:11 UTC, dr3 commented on src/app/containers/Timestamp/index.jsx
> +  return now - milliseconds <= 10 * 60 * 60 * 1000;
Feels like we need more unit tests for this..., seeing as we missed it

2019-04-01 11:55 UTC, pjlee11 commented on src/app/containers/Timestamp/index.jsx
> +          Updated {humanReadable(lastPublished)}
Acknowledging that this is hardcoded to the English translation for `Updated` as we will be implementing a internationalisation library when include other services/languages

2019-04-01 11:59 UTC, pjlee11 commented on src/app/containers/Timestamp/timestampUtilities.test.js
> +      const buffer = 100; // allow 100 milliseconds computation time as Date.now() value is different by the time we call `isTenHoursAgoOrLess`
Rather than over complicating this with a `buffer` should we not just give the example of `5 hours ago` or `9 hours ago`?

2019-04-01 12:00 UTC, pjlee11 submitted a review, later dismissed
LGTM 👍

2019-04-01 13:53 UTC, dr3 requested changes
V nice refactor, just a couple things

2019-04-01 13:53 UTC, dr3 commented on src/app/components/Timestamp/index.jsx
> +  <StyledTimestamp as="time" dateTime={datetime}>
Does this need to be `as="time"`, cant it be a styled `time` element originally?

2019-04-01 13:53 UTC, dr3 commented on src/app/containers/Timestamp/index.jsx
>  const longNumeric = {
These are veerrrrry coupled with formatUnixTimestamp, can you import these in from another file?

2019-04-01 14:02 UTC, dr3 commented on src/app/containers/Timestamp/index.jsx
> +        {humanReadable(firstPublished)}
Just noticed this, have the requirements changed? i thought the 'first published' date shouldn't be relative?

2019-04-01 14:53 UTC, dr3 submitted a review, later dismissed
LGTM, great work

2019-04-01 14:56 UTC, dr3 submitted a review, later dismissed

2019-04-02 07:16 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +  it('should render relative time for lastUpdated if < 10 hrs ago, but absolute time for firstUpdated', () => {
```suggestion
  it('should render relative time for lastPublished if < 10 hrs ago, but absolute time for firstUpdated', () => {
```

2019-04-02 07:18 UTC, twinlensreflex reviewed
I think this naming is more consistent with the data used

2019-04-02 07:18 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +  it('should render relative time for lastUpdated if < 10 hrs ago, but absolute time for firstUpdated', () => {
```suggestion
  it('should render relative time for lastPublished if < 10 hrs ago, but absolute time for firstPublished', () => {
```

2019-04-02 07:18 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +  it('should render absolute time for lastUpdated and for firstUpdated if > 10 hrs ago', () => {
```suggestion
  it('should render absolute time for lastPublished and for firstPublished if > 10 hrs ago', () => {
```

2019-04-02 07:31 UTC, twinlensreflex reviewed
I think we could use the `timestampGenerator` imported on line 5 for these

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const publishedFourHoursAgo = now - 1000 * 60 * 60 * 4;
```suggestion
    const publishedFourHoursAgo = timestampGenerator({ hours: 4 });
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const now = Date.now();
```suggestion
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const now = Date.now();
```suggestion
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const firstPublishedEightHoursAgo = now - 1000 * 60 * 60 * 8;
```suggestion
    const firstPublishedEightHoursAgo = timestampGenerator({ hours: 8 });
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const lastPublishedFourHoursAgo = now - 1000 * 60 * 60 * 4;
```suggestion
    const lastPublishedFourHoursAgo = timestampGenerator({ hours: 4 });
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const now = Date.now();
```suggestion
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const firstPublishedTwelveHoursAgo = now - 1000 * 60 * 60 * 12;
```suggestion
    const firstPublishedTwelveHoursAgo = timestampGenerator({ hours: 12 });
```

2019-04-02 07:31 UTC, eleanombre commented on src/app/containers/Timestamp/index.test.jsx
> +    const lastPublishedElevenHoursAgo = now - 1000 * 60 * 60 * 11;
```suggestion
    const lastPublishedElevenHoursAgo = timestampGenerator({ hours: 11 });
```

2019-04-02 10:00 UTC, twinlensreflex approved these changes

2019-04-02 10:07 UTC, dr3 approved these changes

2019-04-03 11:25 UTC, merged