Add codeowners to simorgh
bbc/simorgh pull request #1558
Opened 2019-04-09 16:50 UTC by benjaminhobbs

Resolves n/a

**Overall change:** Adds codeowners

**Code changes:**

Only adds code owners

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-04-09 16:59 UTC, dr3 submitted a review, later dismissed

2019-04-09 17:01 UTC, pjlee11 approved these changes

2019-04-09 17:13 UTC, pjlee11 requested changes
Realistically the `.github/CODEOWNERS` file should be locked down to `@benjaminhobbs` and `@jamesdonoh` because I shouldn't be empower to define ownership across any part of the `simorgh` application. 

Not to say I don't want the power ... 

![](https://media.giphy.com/media/A9grgCQ0Dm012/giphy-downsized.gif)

2019-04-09 17:17 UTC, dr3 approved these changes

2019-04-09 17:24 UTC, pjlee11 approved these changes

2019-04-10 08:26 UTC, sareh approved these changes

2019-04-11 09:13 UTC, merged