multiple captions
bbc/simorgh pull request #1585
Opened 2019-04-11 12:51 UTC by eleanombre

Resolves #1572

**Overall change:** Iterates through blocks in the Caption container in order to render more than one caption (should there be more than one).

**Code changes:**

- I've simplified `renderText()` so that it only renders text
- I've pulled the `<Caption>` element into its own helper function 
- I did this so that making captions by iterating through blocks is more readable
- I've also added the same article data https://www.test.bbc.co.uk/news/articles/cm55llxvqkgo for local testing

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-04-11 15:29 UTC, sareh requested changes
Great work with showing multiple paragraphs in the caption. I've suggested some changes below.

2019-04-11 15:29 UTC, sareh commented on src/app/containers/Caption/index.jsx
> +        block.model.blocks[0].model.blocks,
There's a [deepGet utility that you can use](https://github.com/bbc/simorgh/blob/latest/src/app/helpers/json/deepGet.js), that is a safer way to access deeply nested items in JSON. 
```suggestion
        deepGet(['model', 'blocks', [0], 'model', 'blocks'], block)
```

2019-04-11 15:29 UTC, sareh commented on src/app/containers/Caption/index.jsx
> +    renderCaption(block.model.blocks, imageCaptionOffscreenText),
Likewise you can use the `deepGet` utility here to safely retrieve the nested blocks. `deepGet(['model', 'blocks'], block)`

2019-04-11 15:29 UTC, sareh commented on src/app/containers/Caption/index.jsx
It seems like you haven't pushed your Storybook changes that you had locally to the branch. Can you please push these?

2019-04-11 15:29 UTC, sareh commented on data/test/news/articles/cm55llxvqkgo.json
> +{
After pushing the Storybook examples, you can remove this extra test article.

2019-04-11 15:33 UTC, dr3 commented on src/app/containers/Caption/index.jsx
> +        block.model.blocks[0].model.blocks,
I think its `0` instead of `[0]`, but yay for safe nested objects :D 🎉

2019-04-15 09:40 UTC, oluoluoxenfree approved these changes

2019-04-15 15:07 UTC, sareh approved these changes
👍 Great work!

2019-04-17 08:51 UTC, jamesbrumpton commented
The general functionality of this looks to be fine. However, when using VoiceOver each line is treated as a separate caption, which means the user will hear "Caption" every time they go to a new line. Is this expected behaviour?

2019-04-18 08:55 UTC, sareh commented
@jamesbrumpton This appears to be the desired functionality, since when going onto the second and subsequent paragraphs in the caption, it clarifies that these are still part of the same caption and that we haven't returned to the article body copy yet.

2019-04-18 08:56 UTC, jamesbrumpton commented
Ok. Happy for this to be merged.

2019-04-18 09:46 UTC, merged