Add frontpage fixture data for hausa,igbo,pidgin,yoruba
bbc/simorgh pull request #1590
Opened 2019-04-12 10:14 UTC by aacn500

Resolves #1546 

**Overall change:** Imports frontpage fixture data to /data

**Code changes:**

- Imports fixture data from ares for the hausa, igbo, pidgin and yoruba services front pages
- Sets up routing for fixture data when running locally
- Adds placeholder service configs for four services
- Ignore `frontpage` directories in data validator

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-04-12 10:17 UTC, dr3 commented on src/app/routes/index.js
> +export const frontpageRegexPath = `/:service(${serviceRegex})`;
I know this doesnt particularly matter for fixture, but I think were going to continue using `.amp` for our frontpages too :)

2019-04-15 10:42 UTC, dr3 requested changes

2019-04-15 10:42 UTC, dr3 commented on src/server/index.jsx
> +  const errorWhenAccessingFile = async dataFilePath => {
As nice as this is, as this is a dev route I dont think we need to be this safe or include a new dependancy. The following should be fine IMO

```
res.sendFile(path, {}, error => {
  if (error) {
    logger.error(error
    res.status(500).send('Unable to find file.');
  }
});
``

2019-04-15 11:27 UTC, dr3 approved these changes

2019-04-15 12:18 UTC, chris-hinds approved these changes
LGTM 👍

2019-04-15 12:50 UTC, sareh approved these changes
👍 Looks good locally!

2019-04-15 13:56 UTC, jamesbrumpton commented
Happy for this to be merged.

2019-04-15 14:00 UTC, merged