Section container
bbc/simorgh pull request #1703
Opened 2019-05-14 08:59 UTC by aacn500

Resolves #1675

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-05-20 09:33 UTC, aacn500 commented
blocked waiting for a non-alpha version of `@bbc/psammead-story-promo-list`

2019-05-22 14:15 UTC, dr3 commented on src/app/containers/FrontPageSection/index.jsx
> +  if (!(group.strapline && group.strapline.name)) {
Can you use `deepGet` here please

2019-05-22 14:17 UTC, dr3 requested changes
Looks great, just a couple things

2019-05-22 14:17 UTC, dr3 commented on src/app/containers/FrontPageSection/index.jsx
> +  const ctx = useContext(ServiceContext);
You can combine these 2 lines with 
```
const { script } = useContext(ServiceContext);
```

2019-05-22 16:17 UTC, dr3 commented on src/app/containers/FrontPageSection/index.jsx
> +  if (!deepGet(['strapline', 'name'], group)) {
Ah soz, can you set this to a variable and use it on line 33 please?

2019-05-22 16:30 UTC, dr3 requested changes

2019-05-22 16:30 UTC, dr3 commented on src/app/containers/FrontPageSection/index.jsx
> +        {group.items.map(item => (
I dont think this checks that the key `items` exists. Can you do
```
const items = deepGet(['items'], group);
```
At the top and then throw null if it is falsey (inc empty)

2019-05-22 21:49 UTC, dr3 approved these changes
Great work, really nice comments and testing :100: 

![](https://media.giphy.com/media/3oEduOnl5IHM5NRodO/giphy.gif)

2019-05-23 08:43 UTC, ghost approved these changes
Great work.

2019-05-23 08:51 UTC, DenisHdz approved these changes
Awesome, we are getting there 🕺🏻

2019-05-23 10:12 UTC, jamesbrumpton commented
LGTM. Happy for this to be merged.

2019-05-23 10:29 UTC, merged