Update README to aid local development for WS sites
bbc/simorgh pull request #1844
Opened 2019-06-01 15:33 UTC by rhell

Resolves #1816 

**Overall change:** Updates `README.md` to document how to access World Service front pages.

**Code changes:**

- Updates `README.md`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-06-04 08:30 UTC, DenisHdz submitted a review, later dismissed
LGTM 👍

2019-06-04 09:32 UTC, aacn500 commented on README.md
> +Article pages are served at routes of the format  `/news/articles/:id` where id is the asset ID generated by the Content Management System.
Thanks for updating the readme! It might be worth adding documentation that persian articles can also be accessed locally

2019-06-04 19:57 UTC, dr3 requested changes
https://github.com/bbc/simorgh/pull/1844#discussion_r290208470

2019-06-05 09:52 UTC, dr3 approved these changes

2019-06-05 09:55 UTC, DenisHdz approved these changes
Prost!

2019-06-05 12:28 UTC, david-boydell commented
Looks good.

2019-06-05 14:41 UTC, merged