Tidy files pt. 2
bbc/simorgh pull request #1941
Opened 2019-06-14 11:13 UTC by rhell

Resolves #1930 & #1535 

**Overall change:** 
Update file structure with regards to helpers and utilities to maintain consistency

**Code changes:**

- Move helpers used in production to `/src/app/lib/utilities`
- Move helpers not used in production to `/src/testHelpers`
- Update readme to document how helpers and utils should be split and folder-ed

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-06-14 13:15 UTC, sareh approved these changes
👍 Looks good!

2019-06-14 13:17 UTC, sareh requested changes
There are some imports that need updating. Please check these with `npm run test:lint`.

```
simorgh/src/app/helpers/pageAnchor.js
  1:22  error  Unable to resolve path to module './onClient'  import/no-unresolved

simorgh/src/app/helpers/pageAnchor.test.js
  2:22  error  Unable to resolve path to module './onClient'  import/no-unresolved

simorgh/src/app/lib/utilities/preprocessor/rules/blockPositioning.js
  1:21  error  Unable to resolve path to module '../../../json/deepGet'    import/no-unresolved
  2:23  error  Unable to resolve path to module '../../../json/deepClone'  import/no-unresolved

simorgh/src/app/lib/utilities/preprocessor/rules/blockPositioning.test.js
  1:23  error  Unable to resolve path to module '../../../json/deepClone'  import/no-unresolved
```

2019-06-14 13:19 UTC, sareh submitted a review, later dismissed
Internet was slow, so didn't see the fix pushed before my comment. Fix looks good, thanks @rhell

2019-06-14 14:14 UTC, dr3 commented
<img src="https://user-images.githubusercontent.com/11341355/59515351-d3cb0300-8eb6-11e9-9af0-52785fc9fd8b.png" width="200px" />

Personaly preference, we have alot of files in these folders, rather than 
```
utils
- deepClone.js
- deepClone.test.js
```
can we do 
```
utils
- deepClone
-- index.js
-- index.test.js
```

2019-06-14 14:58 UTC, benjaminhobbs commented on src/app/lib/README.md
> +The `./utilities` directory is where helpers and utiltiies used in production should be maintained, whereas non-production helpers and utilities should be stored in `../testHelpers`. Helpers nested w
Nicely written

2019-06-14 14:59 UTC, jamesbhobbs approved these changes

2019-06-14 15:01 UTC, dr3 approved these changes
![](https://media.giphy.com/media/X5i2BoQeD9kWY/giphy.gif)

2019-06-14 15:17 UTC, sareh approved these changes

2019-06-17 11:30 UTC, PriyaKR commented
Regression looks good to me.

2019-06-17 12:53 UTC, merged