Canonicals are wrong
bbc/simorgh pull request #1945
Opened 2019-06-14 14:01 UTC by rhenshaw56

Resolves #1836

Changed canonical link from bbc.co.uk to bbc.com

**Code changes:**

- changed origin in getOriginContext.test.js to bbc.com and updated logic accordingly
-  updated tests and snapshots

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-06-17 10:43 UTC, 12 reviewed
Should this not be `.co.uk`?
```html
<link data-react-helmet="true" rel="alternate" href="https://www.bbc.com/news/articles/c6v11qzyv8po" hrefLang="en"/>
```

2019-06-17 10:47 UTC, dr3 requested changes

2019-06-17 10:47 UTC, dr3 commented on src/app/contexts/RequestContext/getOriginContext.js
> +  let origin = 'https://www.bbc.com';
Setting .com as the default has huge affects in the application, we default to .co.uk to ensure that if the application is missing something, we dont accidentally show a UK user something like adverts. Chatting to @sareh this doesn't feel like something we should do to fix a metadata issue. Can you catch up with her please?

2019-06-17 11:01 UTC, rhenshaw56 commented
> Should this not be `.co.uk`?
> 
> ```
> <link data-react-helmet="true" rel="alternate" href="https://www.bbc.com/news/articles/c6v11qzyv8po" hrefLang="en"/>
> ```

@rhell the ticket description required that the canonical url should always be `.com`

2019-06-17 11:07 UTC, jimjohnsonrollings commented
> Should this not be `.co.uk`?
> 
> ```
> <link data-react-helmet="true" rel="alternate" href="https://www.bbc.com/news/articles/c6v11qzyv8po" hrefLang="en"/>
> ```

Original issue speccing alternates is https://github.com/bbc/simorgh/issues/1338
AFAIK it's still correct to have all three alternates, all the time (for /news)

2019-06-18 08:44 UTC, sareh reviewed
Looks great locally. Just added a couple of final comments below.

2019-06-18 08:44 UTC, sareh commented on src/app/containers/StoryPromo/__snapshots__/index.test.jsx.snap
> +    font-size: 1.25rem;
If you could run `npm run updateSnapshots` - these snapshots should not change any longer.

2019-06-18 08:44 UTC, sareh commented on src/app/containers/Metadata/index.jsx
> +  const ampLink = `https://www.bbc.com/${service}/articles/${id}.amp`;
I just checked with @jimjohnsonrollings and the ampLink, which is used for the link: `<link rel="amphtml" href="" />` should vary depending on the origin of the user. 
```suggestion
  const ampLink = `${origin}/${service}/articles/${id}.amp`;
```
Only the canonical link should change.

2019-06-18 09:16 UTC, sareh commented on src/app/containers/Metadata/index.jsx
> +  const { platform } = useContext(RequestContext);
```suggestion
  const { origin, platform } = useContext(RequestContext);
```

2019-06-19 15:24 UTC, 12 approved these changes
Looks good!

2019-06-19 17:20 UTC, dr3 approved these changes

2019-06-20 13:31 UTC, jamesbrumpton commented
LGTM.

2019-06-20 14:20 UTC, merged