Pull in new version of @bbc/psammead-copyright
bbc/simorgh pull request #1953
Opened 2019-06-14 15:54 UTC by rhell

Resolves #1788 

**Overall change:** Pull in `@bbc/psammead-copyright@1.0.0` to allow us to specify the position of the copyright component. Update service configs to define text direction.

**Code changes:**

- Pass `position` prop to `psammead-copyright` based on whether service is `ltr` or `rtl`.
- Define text direction in service configs
- Update snapshots

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-06-17 16:48 UTC, dr3 requested changes

2019-06-17 16:48 UTC, dr3 commented on src/app/lib/config/services/persian.js
> +  dir: 'rtl',
Soz to be a pain, can you add `dir` to all services please?

2019-06-18 08:00 UTC, sareh commented on src/app/containers/Copyright/index.test.jsx
>    imageCopyrightOffscreenText: 'Image source, ',
In addition to Drew's comment -  adding `dir: 'ltr'` in the stubs for the LTR unit test cases.

2019-06-18 08:27 UTC, sareh approved these changes
Looks great. 
<img alt="left right swap" src="https://media.giphy.com/media/JQjRqXDzlTnVpcd5xk/giphy.gif" />

2019-06-18 09:42 UTC, dr3 approved these changes
![](https://media.giphy.com/media/fvwgOui2RBRMA/giphy.gif)

2019-06-18 13:37 UTC, jamesbrumpton commented
LGTM.

2019-06-19 08:02 UTC, merged