Route ws service workers
bbc/simorgh pull request #1965
Opened 2019-06-17 15:42 UTC by dr3

Resolves #1958

**Overall change:** Route service workers to the following URLs, but dont use them in the simorgh client app yet

**Code changes:**

- Route service workers to the following URLs

This doesn't use the service worker at this URL, this work needs to be done quick to unblock the Mozart routing. The usage will follow in another issue.

```
/igbo/sw.js
/pidgin/sw.js
/yoruba/sw.js
/persian/sw.js
```

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-06-17 15:51 UTC, DenisHdz requested changes

2019-06-17 15:51 UTC, DenisBBC commented on src/app/routes/regex/index.js
> +export const frontpageSwRegexPath = `/:service(${serviceRegex})/sw.js`;
Can we have all the Articles `RegexPath` first and then the Front Page ones?

2019-06-17 15:51 UTC, DenisBBC commented on src/app/routes/regex/index.test.js
> +  frontpageSwRegexPath,
Same here with the `imports`

2019-06-17 15:51 UTC, DenisBBC commented on src/server/index.jsx
> +  frontpageSwRegexPath,
Same here :)

2019-06-18 07:23 UTC, j-pendlebury approved these changes
Looks good to me 👍

2019-06-18 07:33 UTC, DenisHdz approved these changes
LGTM :)

2019-06-18 09:56 UTC, david-boydell commented
Awaiting e2e's

2019-06-18 10:04 UTC, david-boydell commented
This is tested and is ready for merge.

2019-06-18 10:06 UTC, merged