Use new service worker routing
bbc/simorgh pull request #2067
Opened 2019-06-24 10:04 UTC by EinsteinCarrey

Resolves #1966

**Overall change:** _Configure frontpages to use the new service worker routes defined in service config._

**Code changes:**

- _Move service worker installation to a separate component inside `App`_
- _Add service worker paths to service config_

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

2019-06-24 19:45 UTC, dr3 approved these changes
<img src="https://media.giphy.com/media/q1kJj7z32QwJW/giphy.gif" width="100%" />

2019-06-25 04:34 UTC, ghost requested changes

2019-06-25 04:34 UTC, sadickisaac commented on src/app/containers/ServiceWorker/index.test.jsx
> +      mount(
You should unmount this after the assertion

2019-06-25 04:34 UTC, sadickisaac commented on src/app/containers/ServiceWorker/index.test.jsx
> +  afterEach(() => {
There is no need to clear mocks

2019-06-25 04:34 UTC, sadickisaac commented on src/app/containers/ServiceWorker/index.test.jsx
> +document.getElementById = jest.fn().mockReturnValue(mockRootElement);
We don't need to mock this

2019-06-25 10:14 UTC, dr3 approved these changes

2019-06-25 12:12 UTC, ghost approved these changes

2019-06-26 13:48 UTC, jblaut commented
@EinsteinCarrey can you take a look at your snapshots tests? Jenkins and Travis seem to be failing

2019-06-27 11:04 UTC, david-boydell commented
Hi @EinsteinCarrey,

I've checked this and the following routes return a 404: 

http://localhost:7080/pidgin/service/sw.js
http://localhost:7080/service/sw.js

I'm not entirely sure what I need to do to get this to work? Any ideas?

2019-06-27 11:41 UTC, EinsteinCarrey commented
@david try replacing `service` with the service name ie. 
[http://localhost:7080/news/articles/sw.js](http://localhost:7080/**news/articles**/sw.js)
[http://localhost:7080/pidgin/sw.js](http://localhost:7080/**pidgin**/sw.js)

2019-06-27 12:34 UTC, david-boydell commented
Ah, cool, thanks @EinsteinCarrey, this is ready for merge.

2019-06-27 12:35 UTC, merged