POC diff checking package-lock against latest
bbc/simorgh pull request #219
Opened 2018-06-29 13:32 UTC by pjlee11

_Check if your local package-lock.json is different on origin, if so update locally._

* [ ] Fixes https://github.com/bbc/simorgh/issues/181
* ~[ ] Tests added for new features~

* ~[ ] Test engineer approval~

2018-07-02 17:25 UTC, jamesbhobbs commented on is-update-required.sh
> +#!/bin/bash
If I make any change to package versions in package.json this will slow every push to origin. --- you've said to me that this is rare, but this is also the only case in which the issue (that started this PR) is relevant is useful re tests passing/not. Although I do admit this PR covers more, I don't agree that always pulling origin is a good thing.

2018-07-02 17:29 UTC, benjaminhobbs commented on is-update-required.sh
> +#!/bin/bash
The changes to package-lock.json aren't committed, so there's no point to this as in CI this is the only thing that's used.

2018-07-02 17:29 UTC, jamesbhobbs requested changes

2018-07-02 17:29 UTC, benjaminhobbs commented on is-update-required.sh
> +#!/bin/bash
If there are conflicts how does this handle it?

2018-07-02 17:39 UTC, benjaminhobbs commented
This goes beyond the scope of the issue to not only `npm install` but also pull origin latest into the branch on push. I think this is very strict and quite slow, but I'm not entirely opposed to it. I do object to this going so far beyond the scope of the issue description though - this needs discussion with the team. IMO you should get used to managing your node modules and know what you have installed as you move between branches.

On a more constructive note... A better alternative to the problem might be a post-merge hook that conditionally `npm install`s then prompts you to commit. - avoiding the issue even earlier in the dev process and not on each push.

2018-07-05 10:03 UTC, pjlee11 commented
Yeah I see your point this is out of scope for the issue. How about instead of being strict by forceably updating and installing the check runs and in the console prompt's the user that the package-lock.json differs to the current one on latest?

2018-07-05 15:14 UTC, pjlee11 commented
At the point of commit f6a07cd I tested the logic as follows by trying `testy-test` as `origin/latest` with package-lock.json changes:

```
// make branch testy-test
git checkout -b testy-test

// update several parts to package-lock.json & commit
git commit -am "edit package-lock.json"

// checkout feature branch
git checkout npm-install-if-package-lock-is-diff

// update command to point at testy-test not origin/latest and try to commit 
git commit -am  "white space commit"
```

**OUTPUT**

```
Found '/Users/phillee/Code/BBC/simorgh/.nvmrc' with version <v8.11>
Now using node v8.11.3 (npm v6.1.0)
Found '/Users/phillee/Code/BBC/simorgh/.nvmrc' with version <v8.11>
Now using node v8.11.3 (npm v6.1.0)
husky > npm run -s precommit (node v8.11.3)

Warning: Your package-lock.json differs to origin/latest with 4 additions
Unless you have made dependency changes on your feature branch it is likely your branch is out of date with origin/latest
We suggest you 'git pull origin latest' and run 'npm install' to update your package-lock.json
This ensures you are running the most recent version and also that the precommit and prepush hooks are valid on you local setup

[npm-install-if-package-lock-is-diff 55d2172] white space commit
 1 file changed, 2 insertions(+), 1 deletion(-)
```



The actual prompt content:

```
Warning: Your package-lock.json differs to origin/latest with 4 additions
Unless you have made dependency changes on your feature branch it is likely your branch is out of date with origin/latest
We suggest you 'git pull origin latest' and run 'npm install' to update your package-lock.json
This ensures you are running the most recent version and also that the precommit and prepush hooks are valid on you local setup
```

2018-07-06 12:28 UTC, pjlee11 commented
Closing this in favour of the solution mentioned here https://github.com/bbc/simorgh/issues/181#issuecomment-403014860

2018-07-06 12:28 UTC, closed without merging