wip: update cypress readme
bbc/simorgh pull request #2205
Opened 2019-07-01 12:56 UTC by thekp

Resolves #1228

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-02 11:15 UTC, thekp commented
i will squash the commits when i merge

2019-07-02 11:17 UTC, benjaminhobbs commented on cypress/README.md
> +- Use the custom commands in `/support/command.js` directory.
Should be that we use the default commands and the custom commands, we don't want a custom command created that is superficially different to the deafult. e.g. the getElement helper currently in /support.

2019-07-02 11:18 UTC, benjaminhobbs commented on cypress/README.md
> +- Write as many tests as you please, but don't make them atomic. i.e. use .and() instead of a second test. -- The runtime of tests matters so make each as fast as you can, avoid repeating expensive t
You've broken the md here

2019-07-02 12:36 UTC, j-pendlebury requested changes
just a couple of typos 🙈

2019-07-02 12:36 UTC, jblaut commented on cypress/README.md
> +\*Config exists in one place. Config for running tests is in /support/config/ and config for expected results should either be hardcoded in a test or imported from application config (for example ser
```suggestion
\*Config exists in one place. Config for running tests is in `/support/config/` and config for expected results should either be hardcoded in a test or imported from application config (for example service translations).
```

2019-07-02 12:36 UTC, jblaut commented on cypress/README.md
>  This folder contains all the simorgh application end-to-end (E2E) tests and exclusively uses cypress as a testing framework. At present we run all E2E tests on all builds and deploys to all environme
```suggestion
This folder contains all the Simorgh application end-to-end (E2E) tests and exclusively uses cypress as a testing framework. At present we run all E2E tests on all builds and deploys to all environments including live.
```

2019-07-02 12:36 UTC, jblaut commented on cypress/README.md
>  - If you're using a let, var or const in any test/helper/command in this repo, you're probably doing it unecessarily, use cypress aliasing or chain requests.
```suggestion
- If you're using a let, var or const in any test/helper/command in this repo, you're probably doing it unnecessarily, use cypress aliasing or chain requests.
```

2019-07-03 10:19 UTC, j-pendlebury approved these changes

2019-07-03 10:40 UTC, jamesbhobbs approved these changes

2019-07-03 10:41 UTC, benjaminhobbs commented
No testing needed

2019-07-03 10:43 UTC, merged