Pull in media indicator to fix ie hover
bbc/simorgh pull request #2208
Opened 2019-07-01 15:01 UTC by dr3

Pulls in https://github.com/bbc/psammead/pull/722

**Code changes:**

- Bump media indicator to pull in https://github.com/bbc/psammead/pull/722

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

2019-07-01 15:03 UTC, DenisHdz approved these changes

2019-07-01 15:06 UTC, ghost approved these changes

2019-07-01 15:08 UTC, ghost requested changes
Update snapshots. CI failing

2019-07-01 15:11 UTC, dr3 commented
Fixed :)

2019-07-01 15:15 UTC, ghost approved these changes

2019-07-02 15:01 UTC, david-boydell commented
This is Ready for Merge

2019-07-02 15:11 UTC, j-pendlebury approved these changes

2019-07-02 15:14 UTC, merged