bump-dependency
bbc/simorgh pull request #2267
Opened 2019-07-03 10:49 UTC by thekp

Resolves: no issue

**Overall change:** combines the following dependabot PRs:

https://github.com/bbc/simorgh/pull/2236
https://github.com/bbc/simorgh/pull/2244
https://github.com/bbc/simorgh/pull/2254
https://github.com/bbc/simorgh/pull/2251
https://github.com/bbc/simorgh/pull/2253
https://github.com/bbc/simorgh/pull/2191
https://github.com/bbc/simorgh/pull/2200

Code Changes:

update package.json
update package-lock
update snapshots

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-03 11:23 UTC, DenisHdz requested changes

2019-07-03 11:23 UTC, DenisBBC commented on package.json
> +    "@bbc/psammead-story-promo-list": "^1.0.1",
Can you bump this one to `1.0.2` since it has been merged this morning?

2019-07-03 12:36 UTC, j-pendlebury approved these changes

2019-07-03 12:58 UTC, DenisHdz approved these changes
Great job 👍

2019-07-04 09:13 UTC, david-boydell commented
All good, this is ready for merge.

2019-07-04 10:00 UTC, merged