put manifest and sw in one file
bbc/simorgh pull request #2645
Opened 2019-07-19 13:07 UTC by oluoluoxenfree

Resolves #2212 

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-22 09:46 UTC, dr3 requested changes

2019-07-22 09:46 UTC, dr3 commented on cypress/support/commands/application.js
> +Cypress.Commands.add('testArticleServiceWorker200s', service => {
These commands are far too specific IMO. Commands should share reusable code around our tests. These can only be used in 1 application.

2019-07-23 09:07 UTC, dr3 requested changes

2019-07-23 09:07 UTC, dr3 commented on cypress/integration/application/index.js
> +        `/${service}/sw.js`,
This loses coverage of `news/articles/sw.js` which were using on Live

2019-07-23 10:03 UTC, benjaminhobbs commented on cypress/integration/application/index.js
> +  ['igbo', 'news/articles', 'pidgin', 'yoruba'].forEach(service => {
I think this block will also pass on live

2019-07-23 11:19 UTC, jamesbhobbs approved these changes

2019-07-23 11:22 UTC, dr3 approved these changes

2019-07-23 11:22 UTC, dr3 commented on cypress/integration/application/index.js
> +    if (service === 'default') {
This can be `.filter(service !== 'default)` above

2019-07-23 11:58 UTC, benjaminhobbs commented
This doesn't need testing

2019-07-23 14:35 UTC, merged