Stop push if not up to date with latest
bbc/simorgh pull request #267
Opened 2018-07-09 18:05 UTC by pjlee11

_Takes the most recent commit from origin/latest and checks for it in a list of all commits in the history of the branch_

* [ ] Fixes https://github.com/bbc/simorgh/issues/261
* ~[ ] Tests added for new features~

* ~[ ] Test engineer approval~

Example of failure:
```
git log origin/latest -n 1 --pretty=format:"%H" // 43591841a34a500a718ee03d33397912871ef2e7 (the most recent commit on origin/latest)
git log --pretty=format:"%H" /* (all the commit history of this branch)
			0d4df4bbabdcddace51724d4a354ab98dc52f847
			4ea650b0a1dd4350d1081ed3fd4206043781c086
			6397453dee3cb35e11b79f6d5c5c6ee8c27ca98c
			34fa4ac856816b4d84e858228fad8d2c87e73073
			289eba6f4cdee1310b9591bad54e0c150779111b
			*/
		
sh upToDateWithLatest.sh // denys the push by exiting the current process
Your branch is not up-to-date with latest. Push to origin denied.
Please pull in the most recent version of origin/latest
```

2018-07-10 11:11 UTC, pjlee11 commented
**Output example**

![image](https://user-images.githubusercontent.com/7791726/42506610-4b078ba6-843a-11e8-9292-2398ce761b9e.png)

2018-07-10 12:28 UTC, BogdanDogaru submitted a review, later dismissed

2018-07-11 10:51 UTC, jtart requested changes
1 minor change. Interested to see it in action so would like to see it merged ASAP.

2018-07-11 10:51 UTC, jtart commented on package.json
> +    "prepush": "./upToDateWithLatest.sh && npm run test:unit",
Please move this to be inside a `scripts` dir.

2018-07-11 11:04 UTC, sareh commented
Agreed that the file should be in a `scripts` directory. When I tried this locally (after making the script file an executable file), I got this error, as expected.
```
Your branch is not up-to-date with latest - push to origin denied.
Please pull in the most recent version of origin/latest. EG: 'git pull origin latest'

husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'git@github.com:bbc/simorgh.git'
```

2018-07-11 11:24 UTC, pjlee11 commented on package.json
> +    "prepush": "./upToDateWithLatest.sh && npm run test:unit",
Done 😎

2018-07-11 11:39 UTC, sareh submitted a review, later dismissed

2018-07-11 11:50 UTC, sareh approved these changes
Looks good!

2018-07-11 11:56 UTC, jtart approved these changes

2018-07-11 12:02 UTC, merged