Refactor metadata helpers
bbc/simorgh pull request #2709
Opened 2019-07-24 11:20 UTC by oluoluoxenfree

Resolves #2222 

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-07-24 16:11 UTC, benjaminhobbs commented on cypress/support/metaTestHelper.js
>  export const retrieve404BodyResponse = (url, bodyResponse) => {
This helper isn't used anywhere so can be deleted

2019-07-24 16:31 UTC, jamesbhobbs requested changes

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/integration/metaArticleSpec.js
>          const currentOrigin = window.location.origin;
These two const are only used once each, remove the consts and just hardcode them inline

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/integration/metaNewsSpec.js
>      const currentOrigin = window.location.origin;
These two const are only used once each, remove the consts and just hardcode them inline

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/support/commands/pageTestFragment/metaData.js
> +  cy.get('head meta[name="fb:admins"]').should(
The three cy.gets here should be chainable as they're all getting things from within head.

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/support/commands/pageTestFragment/metaData.js
> +    cy.get('head meta[name="description"]').should(
Same as above on the the head, I think they can be chained rather than so many cy.gets

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/support/commands/pageTestFragment/metaData.js
> +    cy.get('head meta[name="description"]').should(
Same as above on the the head, I think they can be chained rather than so many cy.gets

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/support/commands/pageTestFragment/metaData.js
> +Cypress.Commands.add('retrieveMetaDataContent', (metaDataTag, content) => {
naming is strange, suggest checkMetadataContent

2019-07-24 16:31 UTC, benjaminhobbs commented on cypress/support/commands/pageTestFragment/metaData.js
> +Cypress.Commands.add('facebookMeta', (fbAdmins, appID, articleAuthor) => {
naming is strange, suggest checkFacebookMetadata

2019-07-24 16:32 UTC, benjaminhobbs commented
It's definitely a lot better than it was, good work

2019-07-29 12:57 UTC, dr3 approved these changes
While I personally disagree with single use cypress commands, this PR does indeed "Refactor the cypress metaData helpers into commands" LGTM

2019-07-30 16:16 UTC, thekp approved these changes

2019-08-01 08:23 UTC, dr3 commented
@benjaminhobbs can you rereview/dismiss requested changes please :)

2019-08-01 09:12 UTC, benjaminhobbs commented on cypress/integration/metaNewsSpec.js
> +    cy.checkArticleMetadata();
Is this necessary? Isn't this tested in metaArticleSpec?

If it is we can get rid of the command and put all those tests directly in the other file.

2019-08-01 12:54 UTC, jamesbhobbs approved these changes

2019-08-01 13:33 UTC, PriyaKR commented
LGTM.

2019-08-01 13:38 UTC, merged