check if dependencies have changed on origin pull
bbc/simorgh pull request #274
Opened 2018-07-11 09:48 UTC by pjlee11

_An executable bash script which checks the local `package-lock` against the `package-lock` origin/latest and if there is significant difference run `npm install` to ensure dependencies are up-to-date_

* [x] Fixes https://github.com/bbc/simorgh/issues/NUMBER
* ~[ ] Tests added for new features~

* ~[ ] Test engineer approval~

![image](https://user-images.githubusercontent.com/7791726/42563988-7e8a5fa4-84f7-11e8-8c88-daad6bb2882b.png)

2018-07-11 11:23 UTC, sareh requested changes

2018-07-11 11:23 UTC, sareh commented on dependencyUpdateCheck.sh
> +      $(git diff origin/latest -- package-lock.json | grep "+  " | wc -l) \
This file should be in a `./scripts` directory.
Can you not use the `$amount_of_additions` value here?
Also, it would be good to print out `now running an npm install`

However, if the `package-lock.json` on latest is different to that locally, shouldn't we have a prompt to do a `git merge origin/latest` first?

2018-07-11 11:30 UTC, pjlee11 commented on dependencyUpdateCheck.sh
> +      $(git diff origin/latest -- package-lock.json | grep "+  " | wc -l) \
I'll move to scripts dir shortly. Yep the variable can be re-used. Adding log to tell the use npm install is being run.

This script is initiated by `post-merge` which runs after another branch has been pulled into the current one. EG: I've just ran "git pulled origin latest" and then this scripts checks if the package-lock dependencies need updating, if so it runs npm install

2018-07-11 11:33 UTC, sareh commented on dependencyUpdateCheck.sh
> +      $(git diff origin/latest -- package-lock.json | grep "+  " | wc -l) \
OK, sounds good.

2018-07-11 11:57 UTC, sareh submitted a review, later dismissed
Looks good!

2018-07-11 12:47 UTC, sareh approved these changes

2018-07-11 14:03 UTC, PaulChinkwende approved these changes

2018-07-11 14:04 UTC, merged

2018-12-04 10:52 UTC, ChrisBAshton commented
Confirmed - our designs have it capped to 1280px. 

![screen shot 2018-12-04 at 10 51 30](https://user-images.githubusercontent.com/5111927/49437097-a3d9cf00-f7b2-11e8-9a11-afe7d575044b.png)