capture requests to nonexistent routes
bbc/simorgh pull request #278
Opened 2018-07-11 15:37 UTC by radiocontrolled

Registers routes for requests to `/article/*` and sends a 404 status code for requests to `/*`.

* [x] Fixes https://github.com/bbc/simorgh/issues/277
* [x] Tests added for new features

* [ ] Test engineer approval

2018-07-12 08:49 UTC, jp-bbc submitted a review, later dismissed
Looks good - approved

2018-07-12 08:52 UTC, BogdanDogaru submitted a review, later dismissed

2018-07-12 08:57 UTC, jtart requested changes

2018-07-12 08:57 UTC, jtart commented on src/server/index.js
> +  .get('/article/*', async (req, res) => {
We shouldn't be setting routing in Express, but in the [config](https://github.com/bbc/simorgh/blob/latest/src/app/routes/index.js#L3-L9) of [React Router](https://reacttraining.com/react-router/) .

The `/*` route is a catch-all and requests will fall through to React Router, which deals with routing.

2018-07-24 10:37 UTC, jtart commented
Closing this PR as we are not prioritising this work yet, and the implementation is not exact to the requirements of the issue. Simpler to start again.

2018-07-24 10:37 UTC, closed without merging