babel-preset-env demo
bbc/simorgh pull request #284
Opened 2018-07-12 14:29 UTC by jp-bbc

_babel-preset-env builds in Razzle. .babelrc features template config for demo purposes._

* [ ] Fixes https://github.com/bbc/simorgh/issues/NUMBER
* [ ] Tests added for new features

* [ ] Test engineer approval

2018-07-13 17:15 UTC, jamesbhobbs submitted a review, later dismissed
This shouldn't be in CR, the tests don't pass.

Based on a 2 second look at the tests you're adding something to build that isn't a production dependency which therefore breaks the production build.

2018-07-18 11:10 UTC, jtart requested changes
You also have conflicts in your webpack bundle files.

2018-07-18 11:10 UTC, jtart commented on .babelrc
> +            "entry": ["babel-polyfill", "./src/client.js"],
This looks like webpack config and should be removed.

2018-07-18 11:10 UTC, jtart commented on .babelrc
> +        }], ["razzle"]
This isn't how we add the razzle babel config, need to do something [like this](https://github.com/jaredpalmer/razzle/#customizing-babel-config).

2018-07-18 11:10 UTC, jtart commented on package.json
> +    "babel-preset-razzle": "^2.0.0",
You don't need to add this.

2018-07-18 15:27 UTC, jtart approved these changes

2018-07-19 09:46 UTC, jamesbhobbs approved these changes

2018-07-19 09:56 UTC, merged