simorgh dependabot updates
bbc/simorgh pull request #2885
Opened 2019-08-05 11:24 UTC by oluoluoxenfree

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-05 16:42 UTC, dr3 approved these changes
LGTM, touches prod deps so will need testing

2019-08-05 16:43 UTC, dr3 requested changes
Snapshots failing and conflicts

2019-08-06 11:44 UTC, oluoluoxenfree commented
@RayNjeri has done a few of these so I'll remove the overlapping ones ( #2863 )

2019-08-07 12:04 UTC, jamesbhobbs requested changes
Also the PR description doesn't list as many issues closed as are in the diff, can you update it please? (and close those PRs as you add them to the PR description)

2019-08-07 12:04 UTC, benjaminhobbs commented on package.json
> +    "@bbc/gel-foundations": "3.2.0",
despite the name I believe this is a psammead package, can we leave it out of this PR please

2019-08-07 12:36 UTC, jamesbhobbs approved these changes

2019-08-07 12:39 UTC, oluoluoxenfree commented
Didn't update audit-ci due to #2955

2019-08-07 12:52 UTC, dr3 approved these changes
LGTM, general build and page view regression IMO. Make sure all builds & loads and is visually the same

2019-08-07 13:16 UTC, benjaminhobbs commented
Manual testing done by Priya and i

2019-08-07 13:28 UTC, merged