Add all services to url list
bbc/simorgh pull request #2956
Opened 2019-08-07 12:47 UTC by EinsteinCarrey

Resolves #NUMBER

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-08 15:34 UTC, dr3 reviewed
Rather than using fs here, and reading (almost) all article fixtures in the data folder, could we use `cypress/support/config/services.js`? If you make it CJS and fake `Cypress.env('APP_ENV')` you can read all the services and paths easily. 

Worth checking with @benjaminhobbs what he thinks though

2019-08-08 15:36 UTC, benjaminhobbs commented
> Rather than using fs here, and reading (almost) all article fixtures in the data folder, could we use `cypress/support/config/services.js`? If you make it CJS and fake `Cypress.env('APP_ENV')` you can read all the services and paths easily.
> 
> Worth checking with @benjaminhobbs what he thinks though

Definitely do this, otherwise our various testing approaches won't ever be kept in lockstep.

2019-08-08 15:36 UTC, jamesbhobbs requested changes
Use the cypress config to get the pages pls

2019-08-08 15:57 UTC, EinsteinCarrey commented
> Rather than using fs here, and reading (almost) all article fixtures in the data folder, could we use `cypress/support/config/services.js`? If you make it CJS and fake `Cypress.env('APP_ENV')` you can read all the services and paths easily.
> 
This is much better than using `fs`, its gonna take more time but I like the approach.

2019-08-09 14:06 UTC, EinsteinCarrey commented
> Rather than using fs here, and reading (almost) all article fixtures in the data folder, could we use `cypress/support/config/services.js`? If you make it CJS and fake `Cypress.env('APP_ENV')` you can read all the services and paths easily.
> 
> @benjaminhobbs @dr3 I made the changes you requested, how does this look?

2019-08-12 15:06 UTC, dr3 reviewed
This is gunna run ~400 times (40 services * 2 pages * 5 breakpoints), seems kinda crazy, could we maybe randomly pick a subset to run on?

2019-08-12 15:24 UTC, jamesbhobbs submitted a review, later dismissed

2019-08-12 15:24 UTC, benjaminhobbs commented on a11y.js
>  const pageWidths = [320, 400, 600, 1008, 1280];
this is unnecessary, can we make this an option to run on all widths and by default only run on 1 mobile width (the one that's most popular)

2019-08-15 12:09 UTC, sadickisaac commented
@dr3  
> could we maybe randomly pick a subset to run on?

This will be non-deterministic. i.e Currently Thai frontpage is failing the `ally` test. If `Thai` is not included in the subset we will have passing tests. If Included it would fail.

![Screenshot 2019-08-15 at 15 08 30](https://user-images.githubusercontent.com/48688870/63093601-947c6980-bf6e-11e9-8de5-9beace0497b2.png)

2019-08-15 12:50 UTC, EinsteinCarrey commented
> @dr3
> 
> > could we maybe randomly pick a subset to run on?
> 
> This will be non-deterministic. i.e Currently Thai frontpage is failing the `ally` test. If `Thai` is not included in the subset we will have passing tests. If Included it would fail.
> 
> ![Screenshot 2019-08-15 at 15 08 30](https://user-images.githubusercontent.com/48688870/63093601-947c6980-bf6e-11e9-8de5-9beace0497b2.png)

@sadickisaac 🤔 somehow `bbca11y` fail on localhost but they pass on Travis and Jenkins
![Screen Shot 2019-08-15 at 3 44 02 PM](https://user-images.githubusercontent.com/21374761/63095505-19b64d00-bf74-11e9-8175-575f03cdab46.png)

2019-08-15 13:05 UTC, sadickisaac commented
@EinsteinCarrey interesting. However my main concern is having a passing `a11y` test while there is a possibility of one or more services failing. We would not be able to notice this early enough if our sample list doesn't contain the failing service(s).

2019-08-15 13:32 UTC, dr3 commented
Can we run just the smoke urls? we recently added a smoke key to the cypress data https://github.com/bbc/simorgh/blob/latest/cypress/support/config/services.js#L46

2019-08-15 14:17 UTC, EinsteinCarrey commented
> @EinsteinCarrey interesting. However my main concern is having a passing `a11y` test while there is a possibility of one or more services failing. We would not be able to notice this early enough if our sample list doesn't contain the failing service(s).

Makes sense, Drew's suggestion should solve for this

2019-08-16 07:37 UTC, dr3 submitted a review, later dismissed
This LGTM, but the a11y test fails, so we cant merge this yet :( Can you write issues to fix the a11y issues, and block this on them please?

2019-08-16 13:07 UTC, EinsteinCarrey commented
blocked on https://github.com/bbc/simorgh/issues/3200

2019-08-16 13:29 UTC, EinsteinCarrey commented
> This LGTM, but the a11y test fails, so we cant merge this yet :( Can you write issues to fix the a11y issues, and block this on them please?

@dr3 I've opened https://github.com/bbc/simorgh/issues/3200 to fix the failing test issue on local but I'm not clear on why it should blocking this PR, I think its a different issue altogether.

2019-08-16 13:52 UTC, dr3 commented
@EinsteinCarrey `npm run bbcA11y` fails for me locally, any idea why its passing on jenkins?

2019-08-21 09:05 UTC, EinsteinCarrey commented
@dr3 Following https://github.com/bbc/bbc-a11y/issues/296, I think we can safely unblock this PR since fixing that issue is outside the scope of this PR.

2019-08-21 11:33 UTC, sadickisaac commented on a11y.js
> +// This functionality should be extended to allow for testing on all widths
```suggestion
// This functionality can be extended to allow for testing on all widths
```

2019-08-21 15:32 UTC, ghost approved these changes

2019-08-22 10:46 UTC, j-pendlebury approved these changes
just one suggestion. Otherwise looks good to me 👍

2019-08-22 10:46 UTC, jblaut commented on a11y.js
> +// Run ally on 360px only since designs are done in this width
```suggestion
// Run a11y on 360px only since designs are done in this width
```

2019-08-23 10:36 UTC, merged