Added all available and relevant producer id's for ATI custom variable
bbc/simorgh pull request #2991
Opened 2019-08-08 10:33 UTC by HarveyPeachey

Resolves #2839

**Overall change:** Added all producer Id's that we have for most of our world services for ATI analytics.

**Code changes:**

- Added ID's based on the routing documentation on the Simorgh [wiki](https://github.com/bbc/simorgh/wiki/Simorgh-Routing) which I cross referenced from our echo docs ATI reporting section [here](http://bbc.github.io/echo-docs/documentation/reporting-ati/#valid-producer-values)
- There weren't any ATI producer codes for the following regions however:
**Cymrufyw
Naidheachdan
Portuguese
Zhongwen**

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-08 11:28 UTC, jimjohnsonrollings commented
Zhongwen should be 38 ('Chinese').
Naidheachdan should be 79 ('Scotland') - but note that Naidheachdan should be a different `s` (aka Destination) as well - 598291 (live) and 598292 (test).
Cymru Fyw should be 100 ('Wales') and the same Destinations as Naidheachdan.

2019-08-08 17:43 UTC, sareh commented
@jimjohnsonrollings
Do Cymru Fyw and Naidheachdan have the same PS/GNL split of destination buckets like News does?
Just wondering, since I believe they are served over both '.co.uk' and '.com'.
https://github.com/bbc/simorgh/blob/bc28bb267d06b839b17aefada7c5ea7e1dcb26b2/src/app/lib/analyticsUtils/index.js#L5

2019-08-08 17:47 UTC, jimjohnsonrollings commented
Oh yes. Good spot. I’ll look up the GNL destinations.  Also this reminds me that Japanese should go in the GNL destination with them instead of WS.

On 8 Aug 2019, at 18:44, Sareh <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimjohnsonrollings<https://github.com/jimjohnsonrollings>
Do Cymru Fyw and Naidheachdan have the same PS/GNL split of destination buckets like News does?
Just wondering, since I believe they are served over both '.co.uk<http://co.uk>' and '.com'.
https://github.com/bbc/simorgh/blob/bc28bb267d06b839b17aefada7c5ea7e1dcb26b2/src/app/lib/analyticsUtils/index.js#L5

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/bbc/simorgh/pull/2991?email_source=notifications&email_token=AB57TYZYPHU7AFJ62UPQFU3QDRLN5A5CNFSM4IKI26M2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD34MFNQ#issuecomment-519619254>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AB57TYZC6YM3HMEB7SFAEVDQDRLN5ANCNFSM4IKI26MQ>.

2019-08-08 17:48 UTC, jimjohnsonrollings commented
That comment via email did not work as well as I’d hoped :(

2019-08-09 08:10 UTC, jimjohnsonrollings commented
So:
GNL_NEWS_LANGUAGES = 598289
GNL_NEWS_LANGUAGES_TEST = 598290

These should be used for:
- Naidheachdan users who are outside the UK
- Cymru Fyw users who are outside the UK
- Japanese (all users)

2019-08-12 08:23 UTC, HarveyPeachey commented
> So:
> GNL_NEWS_LANGUAGES = 598289
> GNL_NEWS_LANGUAGES_TEST = 598290
> 
> These should be used for:
> 
> * Naidheachdan users who are outside the UK
> * Cymru Fyw users who are outside the UK
> * Japanese (all users)

In the logic for working out what destination is chosen based on the location where the user is visiting from it has this: 
`  if (service === 'news') {
    destination = isUK !== false ? 'NEWS_PS' : 'NEWS_GNL';`

Is the logic correct because it's appending "NEWS_PS" and "NEWS_GNL" but as you've stated it's "GNL_NEWS" is there a difference between them in regards to ATI?

2019-08-12 08:25 UTC, jimjohnsonrollings commented
Unfortunately all the systems have different conventions for the order of the naming elements. Ultimately the number is what’s important.

2019-08-12 14:01 UTC, 12 requested changes
Looking good! Got a suggestion though to help keep service-related things all in one place 🙂

2019-08-12 14:01 UTC, 12 commented on src/app/lib/analyticsUtils/index.js
>    const producers = {
I think these would be better homed in the [service configs](https://github.com/bbc/simorgh/tree/latest/src/app/lib/config/services)

2019-08-12 14:30 UTC, jamesdonoh commented on src/app/lib/analyticsUtils/index.js
>    const producers = {
Good idea!

2019-08-13 10:59 UTC, jimjohnsonrollings commented on src/app/lib/analyticsUtils/index.js
>    const producers = {
In future, News won't have a 1:1 service:producer relationship.

2019-08-15 09:36 UTC, 12 commented on src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap
> +exports[`MediaPlayer Fails and returns early when there is no versionId 1`] = `null`;
I don't think this file needs committing.

`git checkout latest -- src/app/containers/MediaPlayer/__snapshots__/index.test.jsx.snap` will reset the file to latest

2019-08-15 13:11 UTC, 12 requested changes
Checking this out locally, I can see that on frontpages, the producer value is no longer being sent (it currently is being sent on test).

Aside from that, this is looking good 👍 

![image](https://user-images.githubusercontent.com/7690572/63096725-8b879a00-bf66-11e9-85dc-586d79af7ecc.png)

2019-08-15 14:11 UTC, HarveyPeachey commented
> Checking this out locally, I can see that on frontpages, the producer value is no longer being sent (it currently is being sent on test).
> 
> Aside from that, this is looking good 👍
> 
> ![image](https://user-images.githubusercontent.com/7690572/63096725-8b879a00-bf66-11e9-85dc-586d79af7ecc.png)

Added the functionality for front pages and media as well. Tested it and it seems to be working fine:

**Front Page**
![Screenshot 2019-08-15 at 15 05 09](https://user-images.githubusercontent.com/4706195/63100394-ed4c0200-bf6e-11e9-842f-d00d8c3ef84a.png)

**Media Page**
![Screenshot 2019-08-15 at 15 04 27](https://user-images.githubusercontent.com/4706195/63100408-f2a94c80-bf6e-11e9-81fe-2f92db060f90.png)

2019-08-19 09:29 UTC, 12 approved these changes
good work 👍

2019-08-20 08:13 UTC, RayNjeri approved these changes

2019-08-20 08:42 UTC, sareh commented
Great work, Harvey!
Since the getDestination method has not been updated in this PR, could you please open a separate PR to add these?
https://github.com/bbc/simorgh/pull/2991#issuecomment-519825139

2019-08-20 08:43 UTC, sareh approved these changes

2019-08-20 08:45 UTC, HarveyPeachey commented
> Great work, Harvey!
> Since the getDestination method has not been updated in this PR, could you please open a separate PR to add these?
> [#2991 (comment)](https://github.com/bbc/simorgh/pull/2991#issuecomment-519825139)

Thanks Sareh, I have a PR open already: #3249 

The code's done I'm just making some unit tests for it.

2019-08-20 09:14 UTC, ryanmccombe approved these changes

2019-08-20 09:38 UTC, merged