Added footer links and labels for Thai
bbc/simorgh pull request #3083
Opened 2019-08-12 13:06 UTC by OlgaLyubin

Resolves #2993 

**Overall change:** Added footer links and labels for Thai 

**Code changes:**
Added appropriate translations to Thai config file.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-12 14:05 UTC, andrew-nowak approved these changes

2019-08-12 14:41 UTC, dr3 approved these changes

2019-08-12 15:24 UTC, DenisHdz requested changes

2019-08-12 15:24 UTC, DenisHdz commented on src/app/lib/config/services/thai.js
> +        text: 'ทำไมคุณจึงไว้วางใจ บีบีซี นิวส์ ได้ ',
```suggestion
        text: 'ทำไมคุณจึงไว้วางใจ บีบีซี นิวส์ ได้',
```

2019-08-12 15:42 UTC, DenisHdz approved these changes

2019-08-13 14:15 UTC, DenisHdz commented
After carried out the a11y swarm we didn't find any issues and this is ready to be tested.

2019-08-14 09:15 UTC, merged