Updating Copyright Cypress test to be include BBC Copyright
bbc/simorgh pull request #3086
Opened 2019-08-12 13:58 UTC by jamesbrumpton

**Overall change:** _Currently, our Copyright tests only test for visible image copyright. However, BBC copyright images have no visible copyright. Whilst there's no visible copyright we can still check to make sure that when the copyright isn't visible that it is returning BBC copyright._

**Code changes:**

- _Changing the command `copyrightDataWindow`._
- _if/else block used to see whether a `<p>` is present within the `figure`._
- _If `<p>` is present `copyrightHolder` data is compared, as per the previous test._
- _If `<p>` isn't present, we assert that the data within `copyrightHolder` is `'BBC'`._
---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-12 14:07 UTC, 12 requested changes

2019-08-12 14:07 UTC, 12 commented on cypress/integration/pages/article/canonical.js
> +
```suggestion
```

2019-08-12 14:07 UTC, 12 commented on cypress/integration/pages/article/canonical.js
> +          })
```suggestion
          });
```

2019-08-12 14:14 UTC, 12 approved these changes
The comment makes things very clear, thanks 👍

2019-08-13 07:33 UTC, RayNjeri approved these changes
LGTM

2019-08-13 08:16 UTC, j-pendlebury approved these changes

2019-08-13 09:14 UTC, merged