add live radio fixture data
bbc/simorgh pull request #3090
Opened 2019-08-12 15:27 UTC by jroebu14

Resolves https://github.com/bbc/simorgh/issues/2754

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-12 15:38 UTC, ryanmccombe approved these changes
This might be the PR to fix that annoying typo in the Afaan Oromoo directory name

2019-08-12 15:41 UTC, pjlee11 commented on data/afaanoromoo/bbc_afaanoromo_radio/liveradio.json
> +        "externalId": "bbc_afaanoromoo_radio",
```suggestion
        "externalId": "bbc_afaanoromoo_radio",
```

If we are having the mapping for `bbc_afaanoromoo_radio` to `bbc_oromo_radio` in simorgh this is likely where we would want to change it

2019-08-12 15:42 UTC, ryanmccombe commented on data/korean/bbc_korean_radio/liveradio.json
> +      "id": "urn:bbc:ares::ws_live:bbc_indonesian_radio",
values here seem wrong

2019-08-12 16:02 UTC, ryanmccombe requested changes
https://github.com/bbc/simorgh/pull/3090#discussion_r312992300

2019-08-13 07:30 UTC, jroebu14 commented
> This might be the PR to fix that annoying typo in the Afaan Oromoo directory name

I think this is the PR that fixed that https://github.com/bbc/simorgh/pull/2947#pullrequestreview-271826277

2019-08-13 09:40 UTC, ryanmccombe approved these changes

2019-08-13 10:59 UTC, pjlee11 approved these changes
LGTM 👍

2019-08-15 11:41 UTC, pjlee11 approved these changes
LGTM 👍

2019-08-15 15:44 UTC, merged