Chartbeat author url bug
bbc/simorgh pull request #3126
Opened 2019-08-14 05:21 UTC by rhenshaw56

Resolves #3040 

**Overall change:** Fix bug with updating chartbeat config when clicking inline link, added author value to config

**Code changes:**

- Added author value to config
- Added current path to config
- Added current path to request context
- Update snapshots

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-14 15:27 UTC, RayNjeri commented on src/app/lib/analyticsUtils/chartbeat/index.js
> +export const getAuthors = (pageType, authors) => {
Consider refactoring 
`export const getAuthors = (pageType, authors) =>  (pageType === 'article' && authors )? authors : 'No Author';`

2019-08-14 16:16 UTC, 12 commented
This is sending two network requests to `ping.chartbeat.net` on page load that have different query params/values
```
http://ping.chartbeat.net/ping?h=test.bbc.co.uk&p=%2Fnews%2Farticles%2Fc0g992jmmkko&u=CrAdAKtKLWsCLGNcG&d=localhost.bbc.com&g=50924&g0=News%2C%20News%20-%20ART&g1=https%3A%2F%2Fwww.facebook.com%2Fbbcnews&g4=New%20Article&n=0&f=e6345&c=0&x=0&m=0&y=3828&o=1093&w=1066&j=45&R=1&W=0&I=0&E=0&e=0&r=&b=277&t=D0wMo7DlEhOvDQ4wrvCasCfPC8QYSb&V=116&z=t%3DDqF_FJBtTwNlBtY6nsY7js8B8i3X4%26E%3D4%26x%3D0%26c%3D0.08%26y%3D3850%26w%3D1066&i=Royal%20wedding%20flowers%20given%20to%20Hackney%20hospice&tz=-60&sn=1&sv=BM6Su5HHgLwDFGkmQC5VRrAD277Bt&sd=7&im=040b0713&_
```
and
```
http://ping.chartbeat.net/ping?h=test.bbc.co.uk&p=%2Fnews%2Farticles%2Fc0g992jmmkko&u=CrAdAKtKLWsCLGNcG&d=localhost.bbc.com&g=50924&g0=News%2C%20News%20-%20ART&g1=https%3A%2F%2Fwww.facebook.com%2Fbbcnews&g4=New%20Article&n=0&f=e6345&c=0&x=0&m=0&y=3850&o=1093&w=1066&j=45&R=1&W=0&I=0&E=0&e=0&v=http%3A%2F%2Flocalhost.bbc.com%2Fnews%2Farticles%2Fc0g992jmmkko&vp=1&b=1078&t=biZqzDGUs8rBrXq420ybq0T_C8J&V=116&z=t%3DD0wMo7DlEhOvDQ4wrvCasCfPC8QYSb%26E%3D0%26x%3D0%26c%3D0.01%26y%3D3850%26w%3D1066&i=Royal%20wedding%20flowers%20given%20to%20Hackney%20hospice&tz=-60&sn=1&sv=BM6Su5HHgLwDFGkmQC5VRrAD277Bt&sd=8&im=04810713&_
```

Also when navigating between articles, I get these errors thrown in console:
```
Warning: Failed prop type: The prop `data.dials` is marked as required in `PageWrapperContainer`, but its value is `undefined`.
Warning: Failed prop type: The prop `data.dials` is marked as required in `DataContainer`, but its value is `undefined`.
```

2019-08-14 17:23 UTC, jamesdonoh commented
Rhys' observation definitely needs investigating.

Also we need to make sure this is tested as working as expected for front pages too as Chartbeat has been added recently for them too.

2019-08-15 09:46 UTC, 12 commented on src/app/containers/ArticleMain/__snapshots__/index.test.jsx.snap
> +  currentPath={null}
Should this really be `null`? I'd expect `currentPath` to always have a value...

2019-08-15 09:49 UTC, 12 commented on src/app/containers/PageHandlers/__snapshots__/withContexts.test.jsx.snap
> +        currentPath={null}
Same question as before

2019-08-15 09:49 UTC, 12 commented on src/app/containers/PageHandlers/withContexts.jsx
> +    currentPath: string,
We should always have a `currentPath` right? I don't see why this can't be a `required` prop.

2019-08-15 09:52 UTC, dr3 submitted a review, later dismissed
Can we not just use location.pathname wherever we use it?

2019-08-16 07:31 UTC, rhenshaw56 commented
> This is sending two network requests to `ping.chartbeat.net` on page load that have different query params/values
> 
> ```
> http://ping.chartbeat.net/ping?h=test.bbc.co.uk&p=%2Fnews%2Farticles%2Fc0g992jmmkko&u=CrAdAKtKLWsCLGNcG&d=localhost.bbc.com&g=50924&g0=News%2C%20News%20-%20ART&g1=https%3A%2F%2Fwww.facebook.com%2Fbbcnews&g4=New%20Article&n=0&f=e6345&c=0&x=0&m=0&y=3828&o=1093&w=1066&j=45&R=1&W=0&I=0&E=0&e=0&r=&b=277&t=D0wMo7DlEhOvDQ4wrvCasCfPC8QYSb&V=116&z=t%3DDqF_FJBtTwNlBtY6nsY7js8B8i3X4%26E%3D4%26x%3D0%26c%3D0.08%26y%3D3850%26w%3D1066&i=Royal%20wedding%20flowers%20given%20to%20Hackney%20hospice&tz=-60&sn=1&sv=BM6Su5HHgLwDFGkmQC5VRrAD277Bt&sd=7&im=040b0713&_
> ```
> 
> and
> 
> ```
> http://ping.chartbeat.net/ping?h=test.bbc.co.uk&p=%2Fnews%2Farticles%2Fc0g992jmmkko&u=CrAdAKtKLWsCLGNcG&d=localhost.bbc.com&g=50924&g0=News%2C%20News%20-%20ART&g1=https%3A%2F%2Fwww.facebook.com%2Fbbcnews&g4=New%20Article&n=0&f=e6345&c=0&x=0&m=0&y=3850&o=1093&w=1066&j=45&R=1&W=0&I=0&E=0&e=0&v=http%3A%2F%2Flocalhost.bbc.com%2Fnews%2Farticles%2Fc0g992jmmkko&vp=1&b=1078&t=biZqzDGUs8rBrXq420ybq0T_C8J&V=116&z=t%3DD0wMo7DlEhOvDQ4wrvCasCfPC8QYSb%26E%3D0%26x%3D0%26c%3D0.01%26y%3D3850%26w%3D1066&i=Royal%20wedding%20flowers%20given%20to%20Hackney%20hospice&tz=-60&sn=1&sv=BM6Su5HHgLwDFGkmQC5VRrAD277Bt&sd=8&im=04810713&_
> ```

@12 I reached out to Chartbeat support on this and they confirmed that this is an expected behavior, which also the same behaviour on http://www.bbc.com/arabic

2019-08-19 07:23 UTC, RayNjeri approved these changes

2019-08-19 07:27 UTC, ghost approved these changes

2019-08-19 09:06 UTC, 12 requested changes
We need to remove the `author` tag from the Chartbeat config

Other than that, looks good

2019-08-19 12:20 UTC, rhenshaw56 commented
> We need to remove the `author` tag from the Chartbeat config
> 
> Other than that, looks good

@12 done!

2019-08-19 16:19 UTC, 12 approved these changes
Nice one 👍

2019-08-19 16:34 UTC, merged