Filter both cpsTypes and assetTypeCodes
bbc/simorgh pull request #3132
Opened 2019-08-14 09:08 UTC by Bopchy

Resolves #2990 

**Overall change:** _Adds filterUnknownAssetTypeCodes() which filters `assetTypeCodes` to cpstypes.js._

**Code changes:**

- _Add getRelevantGroup()._
- _Add filterUnknownAssetTypeCodes()._
- _Add tests for filterUnknownAssetTypeCodes()._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

2019-08-19 14:36 UTC, DenisHdz requested changes
LGTM, just one refactor :)

2019-08-19 14:36 UTC, DenisHdz commented on src/app/containers/StoryPromo/LinkContents/index.jsx
```
const getContent = () => {
    if (headlines === null) {
      return pathOr(null, ['name'], item);
    }
    const { headline, overtyped } = headlines;
    return overtyped || headline;
  };

  const content = getContent();
```

2019-08-20 10:18 UTC, j-pendlebury approved these changes
Woo looks great 😄👍

2019-08-20 11:30 UTC, DenisHdz approved these changes

2019-08-21 09:50 UTC, david-boydell commented
Looks good, this is ready for merge.

2019-08-22 13:17 UTC, merged