Refactor embedUrl to create base URL from origin
bbc/simorgh pull request #3143
Opened 2019-08-14 14:12 UTC by 12

Resolves #3133 

**Overall change:** Instead of varying the base URL for AV embeds based on what's defined in `envConfig` files, we should vary it based on the `origin` set in `RequestContext`.

**Code changes:**

- New `buildBaseUrl` method that will build an embed URL based on the `origin` it is passed.
- Pass `origin` from `RequestContext` to `embedUrl` helper
- Better testing of `embedUrl` helper function

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

2019-08-14 15:09 UTC, dr3 commented on src/app/containers/MediaPlayer/helpers/embedUrl.js
> +  const baseUrl = `https://www.test.bbc${tld}`;
Just return this, doesn't need to be made into a const :)

2019-08-14 15:09 UTC, dr3 commented on src/app/containers/MediaPlayer/index.jsx
> +  const embedSource = embedUrl(origin, id, versionId, isAmp);
Can you make `embedUrl` take an object as its argument plz

2019-08-14 15:12 UTC, dr3 requested changes
lgtm, just a couple things

2019-08-14 15:55 UTC, dr3 commented on src/app/containers/MediaPlayer/index.jsx
> +    amp: isAmp,
Can we keep this as `isAmp` not `amp` please, after that it has my 👍

2019-08-14 16:05 UTC, dr3 approved these changes

2019-08-15 11:44 UTC, rhenshaw56 approved these changes

2019-08-15 14:00 UTC, merged