e2e tests to ensure no broken links
bbc/simorgh pull request #3199
Opened 2019-08-16 12:58 UTC by PriyaKR

Resolves #2228

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-08-19 13:55 UTC, PriyaKR commented
I have added tests to verify footer links when it comes to header some services seems to have top navigation where the links takes to error pages.

2019-08-20 09:25 UTC, dr3 commented on cypress/integration/pages/index.js
> +        cy.get(' footer a').each(element => {
```suggestion
        cy.get('footer a').each(element => {
```

2019-08-20 09:58 UTC, thekp approved these changes

2019-08-20 10:57 UTC, oluoluoxenfree approved these changes

2019-08-20 14:33 UTC, dr3 approved these changes

2019-08-20 18:06 UTC, jamesbhobbs requested changes
If this is only broken on anchor links then we can run on all envs, but we need to ensure it passes on anchor links - or exclude them in the cy.get(), if this is possible.

2019-08-20 18:19 UTC, dr3 commented on cypress/integration/pages/index.js
> +      it('footer links should not 404', () => {
```suggestion
      it('links should not 404', () => {
```

2019-08-21 13:09 UTC, PriyaKR commented
@benjaminhobbs i tried excluding the anchor links using `cy.get('a')
          .not('[href="#content"]')....` but it appears to throw 404  on some of the nav links
for eg:
2019-08-21 12:46:30 info [server/index.jsx] GET /igbo/egwuregwu 404 153 - 0.593 ms
        2) footer links should not 404

2019-08-21 14:12 UTC, benjaminhobbs commented on cypress/integration/pages/index.js
> +            .not('[href="#content"]')
This seems a little too specific, but a .not (starting with #) would be ideal I think.

2019-08-22 11:08 UTC, jamesbhobbs approved these changes

2019-08-22 11:11 UTC, merged