Bump psammead packages
bbc/simorgh pull request #3274
Opened 2019-08-19 16:34 UTC by thekp

Resolves #NUMBER

**Overall change:** _bumping psammead packages_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [n/a] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [n/a] This PR requires manual testing

2019-08-19 17:39 UTC, jamesbhobbs approved these changes

2019-08-20 09:24 UTC, dr3 approved these changes

2019-08-20 09:26 UTC, andrew-nowak requested changes

2019-08-20 09:26 UTC, aacn500 commented on package.json
> +    "@bbc/psammead-section-label": "^2.3.3",
please pin to 2.1.6

2019-08-20 09:30 UTC, andrew-nowak requested changes

2019-08-20 09:30 UTC, aacn500 commented on package-lock.json
> +      "version": "2.3.3",
you might need to remove the caret from the package-lock; it still seems to have picked >2.1.6 :(

2019-08-20 09:55 UTC, andrew-nowak approved these changes
🙌 lgtm, thanks @thekp

2019-08-20 14:16 UTC, PriyaKR commented
Regression looks good to me.

2019-08-20 14:29 UTC, merged