remove default config
bbc/simorgh pull request #3407
Opened 2019-08-27 10:19 UTC by oluoluoxenfree

Resolves #2654 

**Overall change:** 

Removes the default config, which is unused in the main application and mostly touches a few tests. Updates the affected tests.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-08-27 15:26 UTC, thekp requested changes
we could possibly fix the code climate issue: https://codeclimate.com/github/bbc/simorgh/pull/3407

by creating a function with the repetitive contextProvider logic. 
i.e: something similar to this: https://github.com/bbc/simorgh/blob/latest/src/app/containers/Paragraph/index.test.jsx#L66-L70

2019-08-28 15:11 UTC, thekp approved these changes
![image](https://user-images.githubusercontent.com/30599794/63868433-68b9a480-c9ae-11e9-960f-992ca9f140f0.png)

looks good to me 👍

2019-08-28 15:13 UTC, thekp commented on src/app/containers/ArticleTimestamp/index.test.jsx
> +    isNull('should return null', <WrappedArticleTimestamp />);
i'm not too sure why this has changed 🤔

2019-08-28 19:46 UTC, dr3 approved these changes

2019-08-29 07:40 UTC, staylos92 commented
LGTM 👍

2019-08-29 07:47 UTC, merged