Fixed react warning in FrontPageMain
bbc/simorgh pull request #3459
Opened 2019-08-29 13:41 UTC by lokh01

Resolves #3354 

**Overall change:**
Added in the preprocess rule made in https://github.com/bbc/simorgh/pull/3399

**Code changes:**
- Changed ```filterUnknownContentTypes``` to ```addIdsToItems```
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-08-29 15:51 UTC, dr3 requested changes
LGTM, just 1 small tweak :)

2019-08-29 15:51 UTC, dr3 commented on .env
> +SIMORGH_BASE_URL=http://localhost.bbc.com:7080
need to run `git checkout latest .env`, commit the change and push and then do `git update-index --assume-unchanged .env` :)

2019-09-02 09:35 UTC, thekp approved these changes

2019-09-02 10:17 UTC, dr3 approved these changes

2019-09-02 10:48 UTC, merged