Timestamps in pashto locale
bbc/simorgh pull request #3552
Opened 2019-09-04 10:57 UTC by rhenshaw56

Resolves #3147 

**Overall change:** Pass ps locale to pashto service.

**Code changes:**

- Pass ps locale to pashto service
- use updated version of `psammead-locales`

---
![Screen Shot 2019-09-04 at 11 15 12](https://user-images.githubusercontent.com/25608386/64249202-0c550880-cf0b-11e9-80cd-33d77b07c3e2.png)

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-04 12:14 UTC, jamesdonoh approved these changes

2019-09-04 14:12 UTC, EinsteinNjoroge approved these changes
LGTM
Might require UX approval.

2019-09-06 08:44 UTC, RayNjeri approved these changes

2019-09-06 09:16 UTC, jamesdonoh commented
Blocked till we merge https://github.com/bbc/simorgh/pull/3557

2019-09-10 08:33 UTC, EinsteinNjoroge requested changes
@rhenshaw56 fix conflicts

2019-09-11 08:54 UTC, EinsteinNjoroge approved these changes

2019-09-11 13:43 UTC, merged