Add all 'add to homescreen' assets to the project
bbc/simorgh pull request #3626
Opened 2019-09-09 08:29 UTC by OlgaLyubin

Resolves #3588 

**Overall change:** 
Added assets for all of the services to the project.

**Code changes:**

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-10 12:26 UTC, ghost approved these changes

2019-09-10 13:33 UTC, AlistairGempf approved these changes
Looks good to me

2019-09-10 14:12 UTC, EinsteinNjoroge approved these changes

2019-09-11 09:46 UTC, j-pendlebury approved these changes
![](https://media.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif)

2019-09-17 13:33 UTC, dr3 requested changes

2019-09-17 13:33 UTC, dr3 commented on src/app/lib/config/services/afaanoromoo.js
> +    manifestPath: '/afaanoromoo/manifest.json',
These all need to be `'/manifest.json'` not `'/afaanoromoo/manifest.json'` 🙈

2019-09-18 10:24 UTC, sareh commented on dataValidator/helpers/dataLoader/asyncValidateDir.test.js
> +    await expectMethodToBeCalledTimes(293, readScenarioSpy);
Tests are currently failing on this value.
```suggestion
    await expectMethodToBeCalledTimes(291, readScenarioSpy);
```

2019-09-18 14:15 UTC, dr3 approved these changes
LGTM :)

2019-09-18 14:33 UTC, staylos92 commented
LGTM 👍 

Would need to check this again when the assets are live to ensure the icons are all being picked up correctly.

2019-09-19 08:54 UTC, merged