Crypress tests setup for map pages
bbc/simorgh pull request #3681
Opened 2019-09-10 08:31 UTC by ibMadbouly

Resolves #3455 
Continuing on PR https://github.com/bbc/simorgh/pull/3676 this PR is for building the cypress tests setup for MAP pages  

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- at `cypress/Integration/pages/`: Added new  `pageType` folder for `mediaAssetPage` including these files `index.js` `tests` `testsForAMPOnly` `testsForCanonicalOnly` 

- at `cypress/support/config/services.js`: added the entry for `mediaAssetPage` for the service need to be e2e tested like `pidgin` like 
```js
mediaAssetPage: {
        path:
          Cypress.env('APP_ENV') === 'local'
            ? '/pidgin/tori-49450859'
            : undefined,
        smoke: true,
      }
```

- note: to put the same entry for all other services but no `path` and `smoke` to be `false`

```js
mediaAssetPage: { path: undefined, smoke: false }
```

- Commands : in a separate terminal window run `npm run build && npm start` and in another window to run specific e2e for specific `pageType` use the following command
`/node_modules/.bin/cypress run --spec cypress/integration/pages/mediaAssetPa
ge/index.js`
- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-10 14:44 UTC, jroebu14 commented on src/app/routes/regex/index.test.js
> +    // Accroding to CPS a valid assetUri should have 8 digits or more
typo here

2019-09-10 14:45 UTC, jroebu14 approved these changes
LGTM

2019-09-11 13:37 UTC, ryanmccombe approved these changes

2019-09-11 15:00 UTC, pjlee11 requested changes
Just a couple of changes to cypress tests

2019-09-11 15:00 UTC, pjlee11 commented on cypress/integration/pages/mediaAssetPage/tests.js
> +  describe(`Tests for ${service} ${pageType}`, () => {});
```suggestion
  describe(`No testsThatFollowSmokeTestConfig to run for ${service} ${pageType}`, () => {});
```

2019-09-11 15:00 UTC, pjlee11 commented on cypress/integration/pages/mediaAssetPage/testsForAMPOnly.js
> +}) => describe(`Amp Tests for ${service} ${pageType}`, () => {});
```suggestion
}) => describe(`No testsThatFollowSmokeTestConfigForAMPOnly to run for ${service} ${pageType}`, () => {});
```

2019-09-11 15:00 UTC, pjlee11 commented on cypress/integration/pages/mediaAssetPage/testsForCanonicalOnly.js
> +    describe('Chartbeat', () => {
I don't think this chartbeat test is valid for the live radio page.

2019-09-11 16:11 UTC, pjlee11 approved these changes
LGTM 👍

2019-09-11 17:12 UTC, merged