Use global styles from psammead
bbc/simorgh pull request #3742
Opened 2019-09-16 08:11 UTC by EinsteinCarrey

Resolves #3718 

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-16 10:28 UTC, sareh requested changes
The Storybook update works well. 
For the applicaiton, we need to pass in the fonts to the GlobalStyles component.

2019-09-16 10:28 UTC, sareh commented on src/app/Layouts/defaultPageWrapper.jsx
> +import GlobalStyle from '@bbc/psammead-styles/global-styles';
For consistency with other usage of this import. 
```suggestion
import GlobalStyles from '@bbc/psammead-styles/global-styles';
```

2019-09-16 10:28 UTC, sareh commented on src/app/Layouts/defaultPageWrapper.jsx
>  const PageWrapper = ({ children }) => (
We'll need to pass in the fonts into the GlobalStyles component.

```
import GlobalStyles from '@bbc/psammead-styles/global-styles';
import { ServiceContext } from '../contexts/ServiceContext';
...
const { fonts } = useContext(ServiceContext);
...
<GlobalStyles fonts={fonts} />
```

2019-09-16 11:44 UTC, sareh approved these changes
Great work

✅  Fonts are still loading (checked on News and Persian articles
✅  Normalize still loading
✅  Box-sizing border-box still loading
http://localhost.bbc.com:7080/news/articles/c0g992jmmkko
<img width="1432" alt="Screenshot News article" src="https://user-images.githubusercontent.com/3028997/64955210-88423f80-d87f-11e9-8233-e7be243c1f8d.png">

http://localhost.bbc.com:7080/persian/articles/c4vlle3q337o
<img width="1440" alt="Screenshot Persian article" src="https://user-images.githubusercontent.com/3028997/64955236-9c863c80-d87f-11e9-834a-8d46eb1e2bfe.png">

2019-09-17 09:05 UTC, dr3 approved these changes

2019-09-17 09:06 UTC, jroebu14 approved these changes

2019-09-17 15:14 UTC, paruchurisilpa commented
Looks good to me..

2019-09-19 12:00 UTC, merged