Map fixtures for variants
bbc/simorgh pull request #3775
Opened 2019-09-16 12:54 UTC by pjlee11

Resolves #3772

**Overall change:** Adds support for service with variants for the Media Asset Pages

**Code changes:**

- Enable variant support in the regex, server, getInitalData and fixture data for the mediaAssetPages. 
- Unit tests for all changed logic

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

**Testing:**
With this branch checked out the following URLs should render a page correctly: 

http://localhost.bbc.com:7080/serbian/srbija-49427344/lat
http://localhost.bbc.com:7080/serbian/srbija-49427344/cyr
http://localhost.bbc.com:7080/ukchina/49375846/simp
http://localhost.bbc.com:7080/ukchina/49375846/trad
http://localhost.bbc.com:7080/zhongwen/chinese-news-49631219/simp
http://localhost.bbc.com:7080/zhongwen/chinese-news-49631219/trad

2019-09-16 21:37 UTC, dr3 requested changes
Cyyyyyypprreesssssss

NB: were currently only testing `simp`

2019-09-17 11:01 UTC, pjlee11 commented
@dr3 the Cypress tests for MediaAssetPage on all services that support variants is `mediaAssetPage: { path: undefined, smoke: false },`

2019-09-18 13:36 UTC, dr3 approved these changes

2019-09-18 13:40 UTC, ryanmccombe commented on src/app/routes/getInitialData/mediaAssetPage/index.test.js
> +const defaultServiceParam = 'pidgin';
don't think we use these variables, other than to move them into an object later?

Could just create the object here

2019-09-18 13:41 UTC, ryanmccombe approved these changes

2019-09-18 14:14 UTC, jroebu14 approved these changes
LGTM

2019-09-18 17:11 UTC, merged