Integrate Subheading container into MainContent container
bbc/simorgh pull request #379
Opened 2018-07-26 14:42 UTC by radiocontrolled

This PR whitelists the Subheading container so it can be rendered by the MainContent container.

* [x] Fixes https://github.com/bbc/simorgh/issues/334
* [x] Tests added for new features (i.e., snapshots updated)

* [ ] Test engineer approval

2018-07-26 14:56 UTC, jtart requested changes
Please add subheading data for the MainContent stories - then good to go 👍

2018-07-26 15:11 UTC, jtart approved these changes

2018-07-26 15:23 UTC, PaulChinkwende approved these changes

2018-07-26 15:41 UTC, jp-bbc approved these changes
Looks good - approved

2018-07-26 16:05 UTC, merged

2019-03-22 10:57 UTC, dr3 commented
@ChrisBAshton Can you please move this to psammead