Navigation direction prop
bbc/simorgh pull request #3808
Opened 2019-09-17 09:00 UTC by DenisHdz

Resolves #3720

**Overall change:** 
Pass direction prop to the Navigation to use the right CSS for `ltr` and `rtl`.

**Code changes:**
- Get `dir` prop from config
- Pass `dir` prop to the `Navigation` component
- Update `Navigation` story to use `variant`
- Update snapshots

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [X] This PR requires manual testing

2019-09-17 10:51 UTC, ghost approved these changes

2019-09-17 11:36 UTC, AlistairGempf approved these changes
Looks good

2019-09-17 13:27 UTC, dr3 approved these changes

2019-09-17 13:35 UTC, sareh requested changes
Looks good. However this isn't building on CI since there are duplicate dependencies as a result of pulling in this updated Psammead component. If you run `npm update` and only include the updated `@bbc/psammead-*` packages, that should fix the issue.

2019-09-17 13:44 UTC, DenisHdz commented
> Looks good. However this isn't building on CI since there are duplicate dependencies as a result of pulling in this updated Psammead component. If you run `npm update` and only include the updated `@bbc/psammead-*` packages, that should fix the issue.

@sareh I was wondering what was the issue. Thank you :)

2019-09-17 14:13 UTC, mykeels commented on src/app/containers/Navigation/index.jsx
> +      dir={dir}
Do we need a default value for `dir`, or is there a test to ensure that the value is always set in the service config?

2019-09-17 14:33 UTC, DenisHdz commented on src/app/containers/Navigation/index.jsx
> +      dir={dir}
The `dir` prop is not required in the `Navigation` component and by default is set to `ltr`.

2019-09-18 11:37 UTC, sareh approved these changes

2019-09-19 10:18 UTC, paruchurisilpa commented
Checked that for `rtl` scripts the navigation styling is fine. Looks good to me..

2019-09-19 11:08 UTC, merged