Add focus state to logo on header
bbc/simorgh pull request #387
Opened 2018-07-27 13:04 UTC by briankabiro

_PR changes summary to go here._
- add focus state (styling) to logo
- update snapshots and tests

* [ ] Fixes https://github.com/bbc/simorgh/issues/344
* [ ] Tests added for new features

* [ ] Test engineer approval

2018-07-27 13:32 UTC, sareh commented on cypress/integration/articleSpec.js
> +    anchorElement.should('have.class', 'focus');
The test is failing since you're looking for a class named `focus` on the link.

2018-07-27 15:29 UTC, sareh commented on cypress/integration/articleSpec.js
> +    anchorElement.should('have.class', 'focus');
You also might want to try this, for testing:  
```
    anchorElement.focus();
    shouldContainStyles(
      anchorElement.focused(),
      'border-bottom',
      '4px solid rgb(255, 255, 255)',
    );
```

2018-07-30 08:32 UTC, pjlee11 approved these changes

2018-07-30 08:34 UTC, pjlee11 requested changes
Could you add a `GEL_SPACING_HLF` of 4px to `lib/constants/styles` and then import and use that value instead of set the value directly as 4px

2018-07-30 09:32 UTC, pjlee11 submitted a review, later dismissed

2018-07-30 10:13 UTC, jtart requested changes

2018-07-30 10:13 UTC, jtart commented on cypress/integration/articleSpec.js
> +    shouldContainStyles(
This test should be moved to their own explicit test. That should then be moved to its own header spec file so we can ensure seperation of concerns for testing against ACs.

2018-07-30 10:13 UTC, jtart commented on cypress/integration/articleSpec.js
> +    shouldContainStyles(
All other header tests should be moved to that spec file as well, but that is out of scope of this PR.

2018-07-30 10:13 UTC, jtart commented on cypress/integration/articleSpec.js
> +    shouldContainStyles(
@jamesbrumpton

2018-08-02 09:03 UTC, sareh commented on cypress/integration/headerSpec.js
> +describe('News Article', () => {
This describe block should be named 'Branding' or 'Header'.

2018-08-02 09:15 UTC, sareh submitted a review, later dismissed
👍 Looks good!

2018-08-02 10:00 UTC, jtart commented on cypress/integration/headerSpec.js
> +  it('should render the BBC News branding', () => {
We should probably split these out into individual tests, but fine for now.

2018-08-02 10:00 UTC, jtart submitted a review, later dismissed

2018-08-06 15:23 UTC, PaulChinkwende commented
This PR now fixes two issues as the code for both functionality of hover and focus is extremely similar and interlinked. Issues Fixed:
https://github.com/bbc/simorgh/issues/343
https://github.com/bbc/simorgh/issues/344

2018-08-06 15:50 UTC, PaulChinkwende commented
![header focus state](https://user-images.githubusercontent.com/30601401/43727018-b43e30fc-9998-11e8-9d0e-c0c1b6f620ff.png)
![header hover state](https://user-images.githubusercontent.com/30601401/43727042-c64cea36-9998-11e8-9acc-5b011f34367d.png)

2018-08-07 13:46 UTC, jtart requested changes

2018-08-07 13:46 UTC, jtart commented on cypress/integration/articleSpec.js
> +describe('Article Body Tests', () => {
We should also move https://github.com/bbc/simorgh/pull/387/files#diff-d8b08c81c1b0e31ef3e9bf8a801301e6R18 out of this spec file.

2018-08-07 13:46 UTC, jtart commented on cypress/integration/headerSpec.js
> +  it('should render the BBC News branding', () => {
Now that this is split out, it would be of value to split out the specific assertions into their own test, rather than a generic `should render`.

2018-08-07 13:46 UTC, jtart commented on src/app/lib/constants/styles.js
> +export const GEL_SPACING_HLF = 4;
This should be `GEL_SPACING / 2`.

2018-08-07 13:46 UTC, sareh reviewed
This all looks great! Just one small comment about Cypress test.

2018-08-07 13:46 UTC, sareh commented on cypress/integration/headerSpec.js
> +    anchorElement.focus();
Can you please add another `it` block with `it('should have a focus state'` to surround this assertion?

2018-08-07 14:23 UTC, sareh approved these changes

2018-08-07 14:29 UTC, sareh approved these changes

2018-08-07 14:32 UTC, jtart approved these changes

2018-08-07 15:14 UTC, PaulChinkwende commented
The functionality introduced in this ticket has Passed UX review, however we found that the svg is not vertically centralised in the header. This will be adressed by https://github.com/bbc/simorgh/issues/346.

2018-08-07 15:36 UTC, jamesbrumpton commented
![Alt Text](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.tenor.co%2Fimages%2F43d706607a3de6e9ebbb00262e2a64eb%2Ftenor.gif&f=1)

2018-08-07 15:41 UTC, merged