Fix double counting users
bbc/simorgh pull request #3880
Opened 2019-09-19 16:16 UTC by samora

Resolves #3717 

**Overall change:** We are currently double counting users between Simorgh and Orbit-based pages. This fixes some of that duplication.

**Code changes:**

- Adds `idclient` query param to ATI calls. The value is read from `atuserid` cookie.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

2019-09-19 16:26 UTC, dr3 commented on src/app/lib/analyticsUtils/index.js
> +    const atuserid = Cookie.getJSON('atuserid');
To anyone else curious, `Cookie.getJSON` is fail safe :D https://github.com/js-cookie/js-cookie/blob/155e16b95aa39afc9e8ddbc202a065afee5866b5/src/js.cookie.mjs#L96-L98

2019-09-19 17:26 UTC, dr3 requested changes

2019-09-19 17:26 UTC, dr3 commented on src/app/lib/analyticsUtils/index.js
> +  if (onClient()) {
Can combine these `if`s

```suggestion
  if (onClient() && platform !== 'amp') {
```
Technically, `onClient()` is never true on AMP pages, as we dont run client JS, but nice to be explicty

2019-09-19 17:26 UTC, dr3 commented on src/app/lib/analyticsUtils/index.js
> +    return (atuserid && atuserid.val) || null;
```suggestion
    return pathOr(null, ['val'], atuserid)
```

2019-09-19 18:24 UTC, dr3 commented on src/app/lib/analyticsUtils/index.js
> +  if (platform === 'amp') {
Can remove this `if` now :)

2019-09-20 10:25 UTC, dr3 approved these changes

2019-09-20 10:27 UTC, sareh commented on src/app/lib/analyticsUtils/index.test.js
> +  returnsNullWhenOffClient(getAtUserId);
I think this is missing:
```suggestion
  returnsNullWhenOffClient(getAtUserId());
```

2019-09-20 10:31 UTC, sareh approved these changes
👍 Looks great. Prior to merging, it'd be good for testers to find relevant assets and to ensure the `idclient` query param is being sent in the ATI call on Canonical pages only.

2019-09-20 12:05 UTC, merged