Define Image props
bbc/simorgh pull request #391
Opened 2018-07-30 09:10 UTC by jtart

_PR changes summary to go here._

* [ ] Fixes https://github.com/bbc/simorgh/issues/NUMBER
* [ ] Tests added for new features

* [ ] Test engineer approval

2018-08-01 15:10 UTC, sareh requested changes
Great work with handling the mix of required and optional props for the Image.  
I think it would be best to add some unit tests for a couple of the more complext methods. I've indicated them via comments below.

2018-08-01 15:10 UTC, sareh commented on src/app/containers/Image/index.jsx
> +import { emptyBlockArrayDefaultProps } from '../../models/propTypes';
Would be good to move this function into `../../models/general/index.js`

2018-08-01 15:10 UTC, sareh commented on src/app/models/propTypes/image/index.js
> +  copyrightHolder: string.isRequired,
`copyrightHolder` is not a required attribute. Just checked this with Jim.

2018-08-01 15:10 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +export const arrayOfSpecificBlocks = propTypeData => (props, key) => {
This method is quite complex - I think it should be pulled out into a separate file to have tests run against it.

2018-08-01 15:10 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +const requiredPropCheck = (propData, propTypes) => {
This method should have unit tests.

2018-08-02 15:31 UTC, jtart commented on src/app/containers/Image/index.jsx
> +import { emptyBlockArrayDefaultProps } from '../../models/propTypes';
Should it even exist?

2018-08-06 13:22 UTC, sareh commented on src/app/containers/Image/index.jsx
> +import { emptyBlockArrayDefaultProps } from '../../models/propTypes';
Feel free to remove it, since it is not necessary any longer.

2018-08-07 10:47 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +  type: oneOf([type]).isRequired,
Why is this `oneOf([type]).isRequired`? Should it not be `string.isRequired`, since `type` can be `'rawImage'`, etc.

2018-08-07 11:20 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +  type: oneOf([type]).isRequired,
Discussed with @jtart offline and this usage makes sense.

2018-08-07 11:21 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +  const missingRequiredProps = requiredPropCheck(propData, propTypeData);
Would be good to rename `requiredPropCheck` to be reflective of the fact that it returns missing props that are required.

2018-08-07 11:22 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +    checkPropTypes(propTypes, prop, 'prop', prop.type);
A comment here would be very useful, to clarify what is happening!

2018-08-07 14:13 UTC, sareh commented on src/app/models/propTypes/general/index.js
> +    /**
Thank you for adding such detailed comments here! Makes the file much more readable.

2018-08-07 14:14 UTC, sareh approved these changes
👍 Great work!

2018-08-08 11:09 UTC, jtart commented
This is currently failing because the bundle is getting too large. Marked it as blocked until https://github.com/bbc/simorgh/issues/466 is merged.

2018-08-09 09:28 UTC, BogdanDogaru approved these changes

2018-08-09 10:02 UTC, merged