Localhost and storybook AV support
bbc/simorgh pull request #3939
Opened 2019-09-23 13:18 UTC by pjlee11

Resolves #3931

**Overall change:** Extends the `embedUrl` helper to support multiple types. Changes the live radio `src` to be absolute not relative. 

**Code changes:**

- Extends the `embedUrl` helper to have multiple types and also incorporate the `vpid` for articles into the `assetId` prop
- Uses the `embedUrl` in `MediaPageBlocks/LiveRadio/index.jsx` and now passes in the `origin`
- Adds is `isAmp` logic to the `MediaPageBlocks/LiveRadio/index.jsx`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

Testing notes on the issue.

2019-09-24 14:51 UTC, simonsinclair requested changes
I peer reviewed this with Phil this afternoon (thanks, Phil) and discussed some changes. Please see annotations.

2019-09-24 14:51 UTC, simonsinclair commented on src/app/containers/MediaPlayer/helpers/embedUrl.js
> +const embedUrl = ({ origin, type, assetId, isAmp = false }) => {
Could we rename `assetId` to something like `requestUrl` now that `assetId` and `vpid` are combined?

2019-09-24 14:51 UTC, simonsinclair commented on src/app/containers/MediaPlayer/helpers/embedUrl.test.js
> +    expected: `https://www.bbc.co.uk/ws/av-embeds/articles/${assetId}`,
Could we have a test that shows a new `type`? e.g. media

2019-09-25 10:33 UTC, pjlee11 commented
![image](https://user-images.githubusercontent.com/7791726/65593389-494f7080-df88-11e9-8537-b4d53034f430.png)

2019-09-25 13:53 UTC, dr3 approved these changes
![](https://media.giphy.com/media/wZtxnyxWTImyzpRxf1/giphy.gif)

2019-09-25 14:00 UTC, ryanmccombe approved these changes

2019-09-25 14:01 UTC, simonsinclair approved these changes
The changes look great and the new tests pass. 👍

2019-09-26 13:21 UTC, paruchurisilpa commented
looks good to me..

2019-09-26 13:28 UTC, hindsc52 commented
Admin merging as chromatic build has passed but the status has not updated

![image](https://user-images.githubusercontent.com/14273378/65692085-e3d3b080-e069-11e9-8ba8-b2722bef3504.png)

2019-09-26 13:28 UTC, merged