PWA minor fixes
bbc/simorgh pull request #406
Opened 2018-07-31 15:21 UTC by benjaminhobbs

Minor fixes factored out from https://github.com/bbc/simorgh/pull/394/files
* [x] Part of  https://github.com/bbc/simorgh/issues/72
~~* [ ] Tests added for new features~~

* [ ] Test engineer approval

2018-07-31 16:01 UTC, sareh submitted a review, later dismissed
👍 Looks good!

2018-07-31 16:19 UTC, pjlee11 requested changes

2018-07-31 16:19 UTC, pjlee11 commented on src/app/components/Document/index.jsx
> +        <meta name="theme-color" content="#b80000" />
This hex value should be using the constant `C_POSTBOX`

2018-08-01 10:27 UTC, pjlee11 approved these changes

2018-08-01 12:02 UTC, jtart approved these changes

2018-08-01 12:02 UTC, merged