Box-sizing border-box using injectGlobal
bbc/simorgh pull request #419
Opened 2018-08-01 16:39 UTC by sareh

Added `box-sizing: border-box;` to injectGlobal.

Before this PR, this lighthouse test fails `Content is sized correctly for the viewport`. After this PR, it passes. 

We chose to put this into the global styles rather than Article, so that the other components would appear the same when viewed within the Storybook component library or within the Article.  

Before PR:
<img width="824" alt="screen shot of lighthouse with failing test" src="https://user-images.githubusercontent.com/3028997/43513527-da67add4-9575-11e8-9411-0fd505e0235c.png">

After PR:
<img width="818" alt="screen shot of lighthouse with passing test" src="https://user-images.githubusercontent.com/3028997/43513310-58ff3c76-9575-11e8-8b4c-ec89eb0b5f03.png">

* [x] Fixes https://github.com/bbc/simorgh/issues/410
* [ ] Tests added for new features

* [ ] Test engineer approval

2018-08-01 17:22 UTC, jtart requested changes

2018-08-01 17:22 UTC, jtart commented on src/app/lib/globalStyles.js
> +  * {
It might be better suited to do
```
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
to handle pseudo-elements and to allow elements the ability to change their child elements' box-sizing. 

See https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

2018-08-02 09:18 UTC, jtart approved these changes

2018-08-02 13:58 UTC, BogdanDogaru approved these changes

2018-08-02 13:59 UTC, merged