factor out kill of port and rename snapshot update
bbc/simorgh pull request #421
Opened 2018-08-01 21:39 UTC by benjaminhobbs

Factors out commonly used port kill script.
Renames update snapshots to make clear that it is not running tests.

2018-08-02 07:11 UTC, sareh requested changes

2018-08-02 07:11 UTC, sareh commented on package.json
> -    "test:e2e:storybook": "(lsof -t -i:9001 | xargs kill) && run-p --race storybook cypress:storybook",
Some of these refer to the `9001` storybook port, whilst others refer to the 7080.

2018-08-06 15:26 UTC, sareh approved these changes

2018-08-07 09:25 UTC, jtart approved these changes

2018-08-07 09:25 UTC, merged