added routes for 404 and 500 error pages
bbc/simorgh pull request #4503
Opened 2019-10-31 17:19 UTC by thekp

Resolves #2639

**Overall change:** _Add a fixed route for our error pages, e.g /service/404 and /service/505._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

2019-11-04 09:34 UTC, sadickisaac commented on src/app/containers/Error/index.jsx
> +const ErrorContainer = ({ status, errorCode }) => {
```suggestion
const ErrorContainer = ({ status, errorCode }) => <ErrorMain status={errorCode || status} />
```

2019-11-04 09:36 UTC, ghost submitted a review, later dismissed
Fix failing tests on CI.

2019-11-05 14:46 UTC, sareh requested changes
The implementation works well! Great work. I've added a comment re the cypress tests that should be looked at.

2019-11-05 14:46 UTC, sareh commented on cypress/integration/pages/errorPage404/tests.js
> +    describe(`Test error page routes`, () => {
These tests will pass locally, but fail when running against the Test and Live environments, since the STMs will not be routed yet & Mozart will have not been routed yet.  

So the best way to handle this for now is to wrap these tests in an `if` block. There should be `standaloneErrorPages: true` for local, and `false` for test and live. 
You can add this to the object in the env config file: `cypress/support/config/envs.js`

2019-11-05 16:07 UTC, thekp commented on cypress/integration/pages/errorPage404/tests.js
> +    describe(`Test error page routes`, () => {
would it be cleaner to just add `if (Cypress.env('APP_ENV') === 'local') {_do test_}` with a comment above it saying to remove once TEST/LIVE routes are avaliable, then I don't have to update the env config and import it.

2019-11-05 16:37 UTC, sareh commented on cypress/integration/pages/errorPage404/tests.js
> +      describe(`Test error page routes`, () => {
```suggestion
      describe(`${service} error page routes`, () => {
```

2019-11-05 16:38 UTC, sareh approved these changes
👍 Looks great. 

Running cypress tests locally looks good. 
<img width="1090" alt="Screenshot Cypress interactive" src="https://user-images.githubusercontent.com/3028997/68226838-a3f9d480-ffea-11e9-9f90-5bb174ff3170.png">

2019-11-05 16:55 UTC, dr3 commented on cypress/integration/pages/errorPage404/tests.js
> +            failOnStatusCode: false,
Does it need this? they should 200

2019-11-05 16:55 UTC, dr3 commented on cypress/integration/pages/errorPage404/tests.js
> +            failOnStatusCode: false,
Does it need this? they should 200

2019-11-05 16:58 UTC, thekp commented on cypress/integration/pages/errorPage404/tests.js
> +            failOnStatusCode: false,
nope, i'll remove it now 👍

2019-11-05 17:10 UTC, dr3 commented on src/app/containers/App/App.jsx
> +        errorCode: null,
This should technically be `errorCode: nextErrorCode` but as we shouldnt use this in client navigation its fine :)

2019-11-06 14:46 UTC, dr3 approved these changes

2019-11-07 10:16 UTC, merged