Readme testing update
bbc/simorgh pull request #4787
Opened 2019-11-25 15:00 UTC by oluoluoxenfree

Discussed with @jamesdonoh.

Adding more explanation about the environment variables and smoke tests to the main README.

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

2019-11-25 16:23 UTC, amywalkerdev requested changes

2019-11-25 16:23 UTC, amywalker1987 commented on README.md
> +#### Smoke tests
I would rename this full suite of tests or something similar, as we are already stating above that `npm run test:e2e` only runs the smoke tests.

2019-11-26 16:02 UTC, amywalkerdev approved these changes

2019-11-27 07:21 UTC, EinsteinNjoroge commented on README.md
> +| CYPRESS_SMOKE        | Runs only smoke tests if true                                                                                 | boolean                                           |
```suggestion
| CYPRESS_SMOKE        | Runs only smoke tests if true                                                                                 | `true`, `false`                                          |
```

2019-11-27 07:21 UTC, EinsteinNjoroge commented on README.md
> +| CYPRESS_UK           | See [running e2es in the UK against Live](https://github.com/bbc/simorgh/#running-e2e-in-the-uk-against-live) | boolean                                           |
```suggestion
| CYPRESS_UK           | See [running e2es in the UK against Live](https://github.com/bbc/simorgh/#running-e2e-in-the-uk-against-live) | `true`, `false`                                           |
```

2019-11-27 07:21 UTC, EinsteinNjoroge commented on README.md
> +| CYPRESS_SKIP_EU      | See [running e2es outside EU](https://github.com/bbc/simorgh/#running-e2e-outside-eu)                         | boolean                                           |
```suggestion
| CYPRESS_SKIP_EU      | See [running e2es outside EU](https://github.com/bbc/simorgh/#running-e2e-outside-eu)                         | `true`, `false`                                           |
```

2019-11-27 11:27 UTC, andrewscfc approved these changes

2019-11-27 13:51 UTC, merged