Inline links styling
bbc/simorgh pull request #510
Opened 2018-08-16 14:36 UTC by jtart

Resolves #424, #425, #426, #427

_PR changes summary to go here._

- [x] Tests added for new features
- [ ] Test engineer approval

2018-08-16 16:24 UTC, sareh commented on src/app/lib/constants/styles.js
> +export const C_BLUEJAY = '#0f556c';
Could you please make this all caps, for consistency with other constants?

2018-08-16 16:27 UTC, pjlee11 commented on src/app/components/Text/index.stories.jsx
> +  .add('inline linke', () => (
`linke` 🤔

2018-08-16 16:28 UTC, pjlee11 commented on src/app/components/Text/index.test.jsx
> +    <Text text="This is text that contains an [inline link](https://www.bbc.com/news) inside it.." />,
`it..`

2018-08-16 16:34 UTC, jtart commented
![image](https://user-images.githubusercontent.com/16549467/44221767-5fcaac00-a17a-11e8-8bc1-bff2250fa655.png)
default link styles
![image](https://user-images.githubusercontent.com/16549467/44221782-707b2200-a17a-11e8-894c-8b7b7d52a996.png)
hover styles
![image](https://user-images.githubusercontent.com/16549467/44221799-7f61d480-a17a-11e8-987a-45b5aaee632e.png)
focus styles
![image](https://user-images.githubusercontent.com/16549467/44221827-9d2f3980-a17a-11e8-9f3f-8680d2a6f889.png)
visited styles

2018-08-16 16:47 UTC, pjlee11 commented
Suggestion: if UX would like the border bottom to not be slanted on the edges we could try using padding and a border bottom instead of a transparent border all round.

2018-08-20 09:21 UTC, sareh requested changes
It would be better to have `InlineLink` as its own component and imported in within the Text component. This is to give visibility to those using the component library that the InlineLink is self-contained and reusable. 
The bottom border has angled points, which do not match the design and this will likely be picked up by UX in their review.

2018-08-20 13:08 UTC, pjlee11 approved these changes
Nice work 👌

2018-08-20 13:14 UTC, sareh approved these changes
👍 Looks great! Thanks for pulling out `InlineLink` to be a separate component.

2018-08-20 14:53 UTC, jamesbrumpton commented
LGTM

2018-08-20 15:20 UTC, merged