tidy up internal link transformer
bbc/simorgh pull request #5147
Opened 2020-01-14 16:06 UTC by jroebu14

Resolves #NUMBER

**Overall change:** 
_A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**
- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

2020-01-14 16:11 UTC, ryanmccombe commented on src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js
> +const replaceChevrons = text => text.replace('<', '%3C').replace('>', '%3E');
Needs changed to this following the update to fix the chevron issue: https://github.com/bbc/simorgh/pull/5143/files

(also has updated unit tests in that PR)

```suggestion
const replaceChevrons = text => text.replace('<', '&lt;').replace('>', '&gt;');
```

2020-01-14 16:11 UTC, ryanmccombe approved these changes
Looks good - thanks :)

2020-01-15 14:43 UTC, ryanmccombe approved these changes

2020-01-16 09:17 UTC, rebeccamcginn approved these changes
Looking snazzy

2020-01-16 09:19 UTC, jroebu14 commented
> Looking snazzy

Best code review comment I've ever had 😄Thanks!

2020-01-16 18:18 UTC, ryanmccombe requested changes
Live issue - do not merge yet

2020-01-16 18:49 UTC, ryanmccombe commented
This PR needs integrated: https://github.com/bbc/simorgh/pull/5171

2020-01-17 09:17 UTC, rebeccamcginn approved these changes

2020-01-17 10:01 UTC, simonsinclair approved these changes
Nice! We're adding some preprocessors for the PGL pages, which currently mutate the block model. This work provides some great examples of how we could refactor them to avoid doing that.

2020-01-17 10:16 UTC, ryanmccombe approved these changes

2020-01-17 10:18 UTC, merged

2020-01-17 10:20 UTC, jroebu14 commented
> Nice! We're adding some preprocessors for the PGL pages, which currently mutate the block model. This work provides some great examples of how we could refactor them to avoid doing that.

@simonsinclair feel free to give me a shout if you would like to pair or need some pointers when doing that!