Set privacy policy domain
bbc/simorgh pull request #5231
Opened 2020-01-22 13:02 UTC by RichardPK

Resolves #NUMBER

**Overall change:** 
_A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**
- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

2020-01-22 14:34 UTC, LilyL0u commented
Is this for the cookie banner as well as the privacy policy banner?

2020-01-22 15:31 UTC, RichardPK commented
> Is this for the cookie banner as well as the privacy policy banner?

Yes, the `setCookie()` function where we have explicitly declared the domain is used in both. We haven't changed where the function is being called, just how the cookie domains are assigned.

2020-01-23 12:12 UTC, karinathomasbbc requested changes

2020-01-23 12:12 UTC, karinathomasbbc commented on src/app/containers/ConsentBanner/CanonicalLogic/index.js
> +const removeTLDRestriction = domain => {
Can this be renamed to `removeTopLevelDomainRestriction`? (just to avoid more abbreviations :) )

2020-01-23 12:14 UTC, karinathomasbbc approved these changes

2020-01-23 14:03 UTC, jroebu14 commented
@karinathomasbbc made some changes to handle being on test.bbc.com

2020-01-23 14:05 UTC, karinathomasbbc reviewed
Looks good to me!

2020-01-23 14:50 UTC, andrewscfc commented
> It is difficult to test the success of this on live as window.domain points to 'localhost' in local development_

I think you can test this sort of thing by modifying your local host file @RichardPK ?
i.e. add a line to `/etc/hosts` 

e.g.
`127.0.0.1     localhost.bbc.co.uk localhost.bbc.com`

2020-01-23 14:58 UTC, andrewscfc approved these changes
LGTM, if possible try and test locally if my suggestion works: https://github.com/bbc/simorgh/pull/5231#issuecomment-577714475 (I may have overlooked something!)

2020-01-24 07:37 UTC, pharingee approved these changes
LGTM. Small suggestion, maybe we can write a test for `removeDomainRestriction` and ensure it's called during `setCookie` to help future-proof this code?

2020-01-24 08:54 UTC, jroebu14 commented
@pharingee thanks for the suggestion. Good point about adding a new test but I'm not a fan of tests that check certain functions are called because they are coupled to the code and break when code is refactored i.e. they are brittle. I'll write a test that checks the cookie is set with the correct domain.

2020-01-24 11:04 UTC, jroebu14 commented
@pharingee it's not actually possible to check which domain a cookie is stored against, you can only get the key name and value. However I've added tests that check the cookies are stored without domain restrictions

2020-01-24 14:52 UTC, merged