Bumping dependencies
bbc/simorgh pull request #5372
Opened 2020-02-03 12:49 UTC by FK78

Resolves multiple dependabot PRs.

**Overall change:** 
_Bumping dependencies._

**Code changes:**
- _Bump webpack-dev-server from 3.10.1 to 3.10.2 #5348_
- _Bump enzyme-to-json from 3.4.3 to 3.4.4 #5350_
- _Bump @testing-library/jest-dom from 5.0.2 to 5.1.0 #5354_
- _Bump jsdom from 16.0.1 to 16.1.0 #5355_
- _Bump @babel/runtime from 7.8.3 to 7.8.4 #5362_
- _Bump eslint-plugin-react from 7.17.0 to 7.18.2 #5366_-

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

2020-02-03 15:47 UTC, HarveyPeachey approved these changes
👍

2020-02-03 15:49 UTC, j-pendlebury requested changes
There are some `eslint` issues, which is why Jenkins is failing:
```
src/app/containers/ArticleMetadata/index.jsx
   6:3   error  'articleId' is missing in props validation               react/prop-types
  54:15  error  'linkedData' PropType is defined but prop is never used  react/no-unused-prop-types
```

2020-02-03 15:51 UTC, HarveyPeachey commented
> There are some `eslint` issues, which is why Jenkins is failing:
> 
> ```
> src/app/containers/ArticleMetadata/index.jsx
>    6:3   error  'articleId' is missing in props validation               react/prop-types
>   54:15  error  'linkedData' PropType is defined but prop is never used  react/no-unused-prop-types
> ```

@jblaut Fahad's got a PR to fix that: https://github.com/bbc/simorgh/pull/5380

2020-02-04 11:22 UTC, jblaut commented on package.json
> +    "eslint-plugin-react": "7.18.2",
```suggestion
    "eslint-plugin-react": "^7.18.2",
```

2020-02-04 11:23 UTC, j-pendlebury approved these changes
Just one suggestion, but otherwise looks good 👍

2020-02-04 12:38 UTC, merged