Article Container/Component update
bbc/simorgh pull request #549
Opened 2018-08-23 08:27 UTC by sareh

Resolves #NUMBER

Call MainContent Container from Article Container

- [ ] Tests added for new features
- [ ] Test engineer approval

2018-08-24 09:23 UTC, pjlee11 submitted a review, later dismissed

2018-08-24 09:55 UTC, pjlee11 submitted a review, later dismissed

2018-08-24 14:23 UTC, jtart requested changes
I can't comment because the line hasn't changed, but I don't think we need this propType now https://github.com/bbc/simorgh/pull/549/files#diff-5f296fd8afe33a8853c3f2655172c257R33

2018-08-24 17:18 UTC, jtart approved these changes

2018-08-28 09:51 UTC, pjlee11 approved these changes

2018-08-28 09:52 UTC, pjlee11 commented on src/app/components/Article/index.jsx
> +  children: node.isRequired,
More of a query than a review point - is it possible to ensure this is at least 2 nodes?
NB: We know a valid article must have a headline and a paragraph hence 2 nodes.

2018-08-28 13:34 UTC, merged