Change articleType to category in samples
bbc/simorgh pull request #599
Opened 2018-09-03 16:14 UTC by jimjohnsonrollings

Resolves #598 

Renames articleType field in sample data to category

- [ ] Tests added for new features
- [ ] Test engineer approval

2018-09-04 07:42 UTC, jtart submitted a review, later dismissed

2018-09-04 09:02 UTC, sareh requested changes
You will need to also change the `articleType` for the two Production articles and in these files:
`data/schema.yaml`
`src/app/containers/Article/index.test.jsx`
`src/app/dataValidator/helpers/validators/validateEnum.test.js`
`src/app/dataValidator/helpers/validators/validateNode.test.js`
`src/app/models/propTypes/article/index.js`

2018-09-05 16:36 UTC, sareh approved these changes
Looks great!

2018-09-05 17:00 UTC, pjlee11 approved these changes

2018-09-06 10:51 UTC, merged