Story page RTL
bbc/simorgh pull request #6106
Opened 2020-04-06 15:53 UTC by sareh

Resolves #NUMBER

**Overall change:**
Enables RTL layout for Story Pages

**Code changes:**

- Enables RTL layout for Story Pages

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

2020-04-07 09:46 UTC, FK78 requested changes
```
/var/lib/jenkins/workspace/simorgh_rtl-story-page-53DJ5EZS2734CKT6Q6G2LLSSVKCTQMYLGZRW2IUOQNQ7BNN3HGGA@2/src/app/containers/ATIAnalytics/index.test.jsx

  8:26  error  Unable to resolve path to module '#pages/StoryPage/fixtureData.json'  import/no-unresolved
```

The import needs to be changed to `import styAssetData from #pages/StoryPage/fixtureData/mundo.json` in `src/app/containers/ATIAnalytics/index.test.jsx`

2020-04-08 15:13 UTC, rhenshaw56 approved these changes

2020-04-08 15:16 UTC, FK78 approved these changes

2020-04-14 08:32 UTC, paruchurisilpa commented
Looks good to me..

2020-04-14 09:13 UTC, merged