Update dependencies
bbc/simorgh pull request #6128
Opened 2020-04-07 15:15 UTC by jblaut

Resolves N/A

**Overall change:**
_A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

2020-04-08 12:04 UTC, Bopchy requested changes
Integration test snapshots need to be updated.

2020-04-16 10:09 UTC, tochwill approved these changes

2020-04-16 10:20 UTC, FK78 approved these changes
👍

2020-04-16 10:21 UTC, Bopchy approved these changes

2020-04-16 14:53 UTC, PriyaKR commented
LGTM.

2020-04-16 15:26 UTC, merged