Create metadata component for article
bbc/simorgh pull request #626
Opened 2018-09-07 09:48 UTC by sareh

Resolves #573

- Moves the Article Metadata into its own component. Nothing should change for existing articles on the front-end. 
- Adds snapshot tests for Metadata, using News and Persian values.
- Tidies up Article stories file, since some props weren't being used. 

- [x] Tests added for new features
- [ ] Test engineer approval

2018-09-07 15:48 UTC, pjlee11 submitted a review, later dismissed
LGTM

2018-09-10 08:23 UTC, jtart requested changes

2018-09-10 08:23 UTC, jtart commented on src/app/components/Article/index.jsx
> +    htmlAttributes,
Rather than define `htmlAttributes` in Article, we should pass `lang` and `amp`, `htmlAttributes` is a react-helmet API.

2018-09-10 08:23 UTC, jtart commented on src/app/components/Article/index.jsx
> +    canonicalLink,
We should just pass here `id` rather than `canonicalLink`, it's not used elsewhere.

2018-09-10 08:29 UTC, jtart approved these changes

2018-09-10 08:30 UTC, jtart commented on src/app/components/Article/index.jsx
> +    htmlAttributes,
@sareh and I decided offline-line that we will continue with the current changes.

2018-09-10 08:30 UTC, jtart commented on src/app/components/Article/index.jsx
> +    canonicalLink,
@sareh and I decided offline-line that we will continue with the current changes.

2018-09-10 08:33 UTC, jtart requested changes

2018-09-10 08:33 UTC, jtart commented on src/app/components/Article/Metadata/index.jsx
> +  htmlAttributes: shape({}).isRequired,
This `htmlAttributes` prop-type should be defined with a `shape` that includes `amp` and `lang`.

2018-09-10 15:27 UTC, pjlee11 submitted a review, later dismissed
LGTM 👍  
Also CodeClimate duplication warning can be ignored

2018-09-11 14:39 UTC, jtart approved these changes

2018-09-11 14:49 UTC, pjlee11 approved these changes

2018-09-11 16:18 UTC, merged