Add routing for articles
bbc/simorgh pull request #627
Opened 2018-09-07 13:01 UTC by thekp

Resolves #NUMBER

_PR changes summary to go here._

- [ ] Tests added for new features
- [ ] Test engineer approval

2018-09-07 15:35 UTC, sareh submitted a review, later dismissed
👍 Great work! Looks good.

2018-09-07 16:20 UTC, jtart requested changes

2018-09-07 16:20 UTC, jtart commented on src/app/containers/Article/index.test.jsx
> +          match: { params: { id: invalidIdParam, service: 'news' } },
This should use the `defaultServiceParam`.

2018-09-10 08:28 UTC, jtart commented on src/app/containers/Article/index.jsx
> +  const services = ['news', 'persian'];
NB: this won't be defined here in the long-term, but it is fine for now.

2018-09-10 08:41 UTC, jtart submitted a review, later dismissed

2018-09-11 14:58 UTC, jtart approved these changes

2018-09-11 15:05 UTC, sareh approved these changes
👍 Looks good!

2018-09-11 15:10 UTC, merged