[2nd try] Reuse Jenkins node and only install/build once
bbc/simorgh pull request #7037
Opened 2020-06-26 13:10 UTC by jamesdonoh

Reverts bbc/simorgh#7024 and resolves https://github.com/bbc/simorgh-infrastructure/issues/1097

For full original details see the original PR: https://github.com/bbc/simorgh/pull/7003

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [NA] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [no] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [no] This PR requires manual testing

2020-06-26 13:33 UTC, chris-hinds requested changes

2020-06-26 13:33 UTC, hindsc52 commented on Jenkinsfile
> +        sh 'npm prune --production'
```suggestion
        pruneDevDependencies()
```

2020-06-26 13:38 UTC, jamesdonoh commented on Jenkinsfile
> +        sh 'npm prune --production'
Oops, thanks!

2020-06-26 13:40 UTC, chris-hinds approved these changes

2020-07-01 16:56 UTC, oluoluoxenfree approved these changes

2020-07-06 08:17 UTC, merged