Bump psammead story-promo-list
bbc/simorgh pull request #7213
Opened 2020-07-14 08:39 UTC by rhenshaw56

Resolves N/A

**Overall change:**
_Bumps psammead story-promo-list to manually regress changes due to #psammead#3588._

**Code changes:**

- _Bump psammead story-promo-list._
- _Update snapshots._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

2020-07-14 08:51 UTC, chris-hinds requested changes

2020-07-14 08:51 UTC, hindsc52 commented on package-lock.json
> +      "resolved": "https://npm.morph.int.tools.bbc.co.uk/jest-silent-reporter/-/jest-silent-reporter-0.2.1.tgz",
Lots of morph npm registries here.

2020-07-14 09:07 UTC, rhenshaw56 commented on package-lock.json
> +      "resolved": "https://npm.morph.int.tools.bbc.co.uk/jest-silent-reporter/-/jest-silent-reporter-0.2.1.tgz",
@hindsc52 fixed.

2020-07-14 09:40 UTC, chris-hinds approved these changes

2020-07-14 09:40 UTC, hindsc52 commented on package-lock.json
> +      "resolved": "https://npm.morph.int.tools.bbc.co.uk/jest-silent-reporter/-/jest-silent-reporter-0.2.1.tgz",
Thanks @rhenshaw56

2020-07-14 09:59 UTC, simonsinclair approved these changes

2020-07-15 14:05 UTC, PriyaKR commented
Looks good to me.

2020-07-15 14:36 UTC, merged