Add Facebook metadata
bbc/simorgh pull request #722
Opened 2018-09-26 09:49 UTC by jtart

Resolves #575

_Adds Facebook metadata and tests._

- [x] Tests added for new features
- [ ] Test engineer approval

2018-09-26 13:42 UTC, pjlee11 requested changes

2018-09-26 13:42 UTC, pjlee11 commented on src/app/components/Metadata/index.jsx
> +      <meta name="fb:admin" content={facebookAdmin} />
This should be `name="fb:admins"`

2018-09-26 13:54 UTC, pjlee11 submitted a review, later dismissed
Nice work

2018-10-01 15:42 UTC, sareh submitted a review, later dismissed
👍 Looks good!

2018-10-03 16:57 UTC, pjlee11 submitted a review, later dismissed

2018-10-04 08:45 UTC, sareh submitted a review, later dismissed
👍 Looks good.

2018-10-04 12:50 UTC, pjlee11 approved these changes

2018-10-04 14:06 UTC, sareh approved these changes

2018-10-04 15:09 UTC, merged