Remove image endpoints and default originCode
bbc/simorgh pull request #798
Opened 2018-10-12 14:40 UTC by pjlee11

Resolves #793 

_This PR removes the base path from the image URLs in the fixture data, this aligns with the Optimo data as it only supplies locators. This PR also refactors the originCode logic so that null or empty string origin codes default to `cpsdevpb` this is needed because Optimo currently does not supply an originCode and the work is not yet scoped._

- [x] Tests added for new features
- [ ] Test engineer approval

## Test instructions ##
Unit test and Cypress tests should cover these changes, I also suggest a basic manual regression to ensure images load

2018-10-12 15:03 UTC, radiocontrolled requested changes
LGTM -I  like the improved test descriptions

I approve pending a change to not use `let` which I have requested a change for.

2018-10-12 15:03 UTC, radiocontrolled commented on src/app/containers/Image/index.jsx
> +
I think you can do: 
` const overridableOriginCode = originCode || 'cpsdevpb';`

This allows avoidance of using `let`

2018-10-12 15:08 UTC, pjlee11 commented on src/app/containers/Image/index.jsx
> +
Good point, will change

2018-10-12 15:09 UTC, radiocontrolled approved these changes
⚽️

2018-10-15 09:25 UTC, jtart approved these changes

2018-10-15 13:13 UTC, merged