Create initial readme file
bbc/simorgh pull request #947
Opened 2018-11-14 11:12 UTC by dr3

Resolves #912

Adds a `README.md` file to the Header component with an explanation of what the component does, how it should be used, how it shouldn't be used.

- [ ] Tests added for new features
- [ ] Test engineer approval

2018-11-15 08:36 UTC, ChrisBAshton requested changes
A typo, and then a couple of things to clarify I think. 👍

2018-11-15 08:36 UTC, ChrisBAshton commented on src/app/components/Header/README.md
> +This component functions as a wrapper for the [Brand](../Brand) component which is also used in the [Footer](../Footer). The wrapper is a HTML 'header' element with the 'role' of 'banner' for accessi
```suggestion
This component functions as a wrapper for the [Brand](../Brand) component (which is also used in the [Footer](../Footer)). The wrapper is a HTML 'header' element with the 'role' of 'banner' for accessibility. This component is distinct from Brand as the 'header' HTML element is unique and cannot be reused elsewhere on the page.
```

2018-11-15 08:36 UTC, ChrisBAshton commented on src/app/components/Header/README.md
> +As this component uses the [Brand](../Brand) which consumes the service context via the [ServiceContextConsumer](../ServiceContextConsumer) component.
This sentence looks unfinished...?

2018-11-15 08:36 UTC, ChrisBAshton commented on src/app/components/Header/README.md
> +Link (NB: Sits within header)
These two lines feel a bit redundant (what are they for?)

2018-11-15 10:36 UTC, ChrisBAshton approved these changes

2018-11-15 14:27 UTC, jtart approved these changes

2018-11-16 10:59 UTC, dr3 commented
Putting in test, just needs merging

2018-11-16 14:09 UTC, jamesbrumpton commented
👍

2018-11-19 12:45 UTC, merged