Creare Headings README.md
bbc/simorgh pull request #968
Opened 2018-11-19 12:30 UTC by dr3

Resolves #915

Adds a readme to the headings component

- ~[ ] Tests added for new features~
- ~[ ] Test engineer approval~

2018-11-19 16:02 UTC, bcmn commented on src/app/components/Headings/README.md
> +The Headings are a set of two components, `Headline` and `Subheading`. They use a `h1` and `h1` HTML element respectively, with the `Headline` being designed for a single use on the page, with `Subhe
> They use a `h1` and `h1` HTML element respectively

I assume the second of these is incorrect? 😛

2018-11-19 16:05 UTC, bcmn requested changes

2018-11-19 16:05 UTC, bcmn commented on src/app/components/Headings/README.md
> +The Headings are a set of two components, `Headline` and `Subheading`. They use a `h1` and `h1` HTML element respectively, with the `Headline` being designed for a single use on the page, with `Subhe
```suggestion
The Headings are a set of two components, `Headline` and `Subheading`. They use a `h1` and `h2` HTML element respectively, with the `Headline` being designed for a single use on the page, with `Subheading` being aimed at repeated use.
```

2018-11-19 16:05 UTC, bcmn commented on src/app/components/Headings/README.md
> +These components can be used at any point on the page, however the `Headline` is designed to be used once at the top of the page. The `Subheadline` adds an `id` value to the `h2` which can be used as
```suggestion
These components can be used at any point on the page, however the `Headline` is designed to be used once at the top of the page. The `Subheadline` adds an `id` value to the `h2` which can be used as an anchor when referencing content.
```

2018-11-19 16:10 UTC, bcmn approved these changes

2018-11-19 16:14 UTC, jtart approved these changes

2018-11-20 10:21 UTC, jamesbrumpton commented
👍

2018-11-20 16:21 UTC, merged