Update Visually Hidden Text README.md
bbc/simorgh pull request #984
Opened 2018-11-22 12:07 UTC by bcmn

Follow-up to #918 

I'd hoped to run the README past Catharine when it reached the UX/a11y review section, but it was merged pretty quickly! Catharine had a few notes on things to clarify, so I've tried to incorporate them.

- [ ] ~Tests added for new features~
- [ ] ~Test engineer approval~

2018-11-22 13:32 UTC, ChrisBAshton requested changes
Otherwise looks good!

2018-11-22 13:32 UTC, ChrisBAshton commented on src/app/components/VisuallyHiddenText/README.md
> +Similarly, when adding hidden text that will occur partway through an article, avoid using phrases that may imply that the main body is over. Suddenly hearing a phrase like "Read more on ___" may sug
Markup is borked by the example text, so:

```suggestion
Similarly, when adding hidden text that will occur partway through an article, avoid using phrases that may imply that the main body is over. Suddenly hearing a phrase like "Read more on [subject]" may suggest to users that they have finished the article. To mitigate this, you may wish to wrap the content in an [`aside` ARIA landmark](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/complementary.html) or include a ["skip link"](https://www.w3.org/TR/WCAG20-TECHS/G1.html), giving users the option to skip back to the main body before the assistive technology reads the full content of the interjection.
```

2018-11-22 14:04 UTC, radiocontrolled submitted a review, later dismissed

2018-11-22 14:28 UTC, radiocontrolled approved these changes
👍

2018-11-26 08:20 UTC, sareh approved these changes
👍 Looks good.

2018-11-26 08:50 UTC, ChrisBAshton approved these changes

2018-11-26 15:08 UTC, jamesbrumpton commented
LGTM

2018-11-27 10:05 UTC, merged