Update Hindi recommendation titles
bbc/simorgh pull request #9920
Opened 2022-03-07 12:23 UTC by MuhammadAHussain

Resolves #9868 

**Overall change:**
We're updating the titles of the recommendations block.

**Code changes:**

- Update the Hindi config to include the updated recommendations.
- Add `moreRecommendationTitle` for the Hindi variation A experiment (https://github.com/bbc/simorgh/issues/9869) to be used in the second block.

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

2022-03-07 12:29 UTC, DarioR01 requested changes

2022-03-07 12:29 UTC, DarioR01 commented on src/app/lib/config/services/hindi.js
> +      recommendationTitle: 'ये भी पढ़ें',
I believe we still need the old title for control.

2022-03-07 12:35 UTC, DarioR01 commented on src/app/lib/config/services/hindi.js
> +      recommendationTitle: 'ये भी पढ़ें',
nvm ignore me

2022-03-07 12:35 UTC, DarioR01 approved these changes

2022-03-07 13:02 UTC, amoore108 approved these changes

2022-03-08 15:07 UTC, pvaliani approved these changes

2022-03-09 12:46 UTC, merged

2022-03-09 16:05 UTC, paruchurisilpa commented
LGTM..
![Uploading Screenshot 2022-03-09 at 15.48.17.png…]()